<title>Math 2210 Fall 2018 (Roby)</title>

<h3>
<span class="mathtitle"><a href="http://www.math.uconn.edu/~troby/math2210f18/index.php"
target="_blank">Tom Roby's Math 2210Q Home Page Fall 2018</a></span><br>
<span class="mathtitle">Applied Linear Algebra
</span> 
</h3>

<img class="mypic" ALIGN=right WIDTH=130 HEIGHT=200 HSPACE=50 src="http://www.math.uconn.edu/~troby/images/bestock09lant.jpg"> 


<h3>Questions or Comments?</h3>
<ul>

  <li><i>For questions about the <b>course material</b> or structure:</i> Please ask in the
  approriate discussion forum in Piazza/HuskyCT. (If you ask me such questions by email, I
  will redirect you there.) You can also talk to your classmates or me during class and
  right afterwards.  

  <li><i>For questions about using HuskyCT:</i> Once you are logged in to <a href="https://learn.uconn.edu/", target="_blank">HuskyCT</a>, click Student Help in the top bar.

   <li><i>For questions about enrollment or suggestions for improving future versions of the
   course:</i> Please email the Professor: <A HREF="mailto:tom.roby@uconn.eduTR">Tom
   Roby</A> (delete initials from end).  

  <li><i>Professor's Homepage:</i> <a href="http://www.math.uconn.edu/~troby">
http://www.math.uconn.edu/~troby</a>
  <li>Office:  MONT 239; Phone:  860-486-8385. <br>
  <li>Office hours:  Thurs 1:50&ndash;2:40 (right after class), 
  <a href="https://zoom.us/j/857139652"> Mon 9PM via Zoom</a>
  and by appointment in MONT 239.  I'm happy to answer
  questions or schedule appointments by email, which I check frequently (except for course content
  questions, which should go to the Piazza online discussion).    
</ul> 

</ul> 

<HR>


<h2>Class Information</h2>


<p class="mathpar"><i> COORDINATES:  </i>  Classes meet Tuesdays and Thursdays
12:30-1:45 in MONT 421.  
<!--  <a href="http://classrooms.uconn.edu/msb215.htm">MSB 215</a>  -->
The registrar calls this Section 007, #5610.</p>  

<p><i> PREREQUISITES:</i> MATH 1132 (Calulus II), 1152 (Honors Calculus
  II), OR 2142 (Advanced Calculus II).</p> 

<p> <i> TEXT:</i> You will need to obtain a copy of the textbook, which is <a href="https://www-math.umd.edu/people/item/380-lay.html">David C. Lay</a>: <a
href="https://www.pearson.com/us/higher-education/product/Lay-Linear-Algebra-and-Its-Applications-5th-Edition/9780321982384.html">
<i>Linear Algebra and Its Applications</i></a>.  Any edition you can find from the 3rd on
should be fine for this class, except that the problem numbers may vary slightly. I recommend any version that
you can get cheaply.  The homework solutions are
written for the <a href="http://www.mypearsonstore.com/bookstore/linear-algebra-and-its-applications-0321385179">4th Ed.</a>; a few of the numerical
problems have different numbers, and a few of the theoretical problems are have different problem numbers.  

<p><i> WEB RESOURCES:</i> The homepage for this course will be available
and updated at  <a
href="http://www.math.uconn.edu/~troby/math2210f18">
http://www.math.uconn.edu/~troby/math2210f18</a>. 
<!--  The textbook author also has   a useful site with review sheets and downloadable data -->
<!--     <a href="http://wps.aw.com/aw_lay_linearalgebra_4">here</a>. -->
 </p>

<p><b><i>HuskyCT:</b></i> We will make limited use of HuskyCT, because of its many deficiencies.
A copy of the course schedule (below) will be posted there that includes links to
solutions for selected HW exercises (which are for your personal use only, not to be
shared). For classroom discussions, we will use Piazza, and assignments will generally be
graded in hardcopy. 
</p>

<p><i>SOFTWARE:</i> In most areas of mathematics it is
  frequently helpful to use computer software not only for computations,
  but also to explore examples, search for patterns, or test
  conjectures.  For linear algebra there are several extensive
  and sophisticated commercial software packages, including MATLAB,
  Maple, and Mathematica.  Matlab is particularly good at linear
  algebra for applications.  All of these can be expensive, depending on
  your site license, but are <a href="http://software.uconn.edu/">currently
  available to UConn students</a>.</p>

<p>An excellent alternative to the above is the free
  open-source computer algebra
  system <a href="http://www.sagemath.org">Sage</a>.  There are many
  commands for linear algebra, and a textbook (linked below) has been
  written that makes significant use of Sage examples.  Sage also
  provides a full-fledged programming environment via the
<a href="http://en.wikipedia.org/wiki/Python_%28programming_language%29">Python
  programming language</a>, but you don't need to be a programmer to use
  it.  I highly recommend trying it out online, and installing a copy
  on your computer.</p>

<p><i> GRADING:</i>  Your grade will be based on two midterm exams, a final
exam, worksheets, homework and participation. </p>

The breakdown of points is:<br> <br>

<center>
<TABLE BORDER="4" CELLPADDING="2">
<tr><th> Midterms <th> Final <th> Quizzes <th> Worksheets  <th> Homework <th> Participation </tr>
<tr><th>20% each <th>30% <th>10% <th> 10% <th> 5% <th>5% </tr>
</TABLE>
</center>
<p></p>

 <p class="mathpar"><i> EXAMS: </i> The exam dates are already scheduled, so please mark
your calendars now (midterms in our classroom on <b>Thursday 27 September</b> and <b>Thursday 1
November</b> at the usual time; the final is TBD by registrar, sometime during the week of
11&ndash;17 December).  All exams (like math itself at this level) are cumulative. No
makeups will be given; instead if you have an approved reason for missing an exam, the final
will count for the appropriately higher percentage. If you miss the final for
reasons <b>approved by the Dean of Students</b>, then you will have one chance to take a
make-up final exam in the second or third week of the following term. </p>

 <p class="mathpar"><i> QUIZZES: </i> Quizzes will be given each Thursday (except midterm
 exam days), covering (a) sections from the previous week (at the level of HW exercises).
 There are no makeup quizzes; however, your
 lowest two quiz scores will be dropped. Here is a
 sample <a href="~troby/math2210f18/Handouts/pq1.pdf">Practice Quiz</a> so you know ahead
 of time what the format will be. (Solutions will be provided below.) </p>



<p><i>STUDENT WORKFLOW:</i> In the course schedule, each section in the text has a single
line indicating the topic, which may correspond to multiple video lectures. For each section
you should:

<ol>
<li> WATCH the VIDEO LECTURE(S) & take notes (pdfs of slides are available);
<li> DO the XIMERA ACTIVIES as a self check;
<li> DO the WORKSHEET problems during classtime and SUBMIT them by the deadline.
<li> USE the PIAZZA DISCUSSION BOARD, CLASSROOM INTERACTIONS, and OFFICE HOURS <b>anytime</b> you get seriously stuck;
<li> CHECK your WORKSHEET against the solutions (posted the morning after the due date);
<li> READ the TEXTBOOK to fill in gaps, see an alternate presentation, straighten out
confusing points; 
<li> DO as many HW problems as you can (prioritizing the <b>mandatory</b> ones, and SUBMIT
them the TUESDAY after that section is covered; 
<li> CHECK your HW against the solutions (posted the morning after the due date);
</ol>

<p>Most weeks we will cover three sections of the text, so many days have multiple sections
due.  The typical pattern will be as follows. </p> 

<p><b>Tuesdays</b> we will engage with worksheets for two sections,
say A and B (so you should have already watched the videos and done the ximera activities
for A and B before then).  You will also hand in HW for the previous week.  </p>

<p> <b>Thursdays</b>, you will hand in the worksheets from the previous Tuesday and take a quiz
on the previous week's material. (This pattern may be disrupted some by midterms and review
sessions.) </p>

<p> This course will be <b>fast-paced</b> and cover quite a bit of material.  
I strongly encourage you to <b>work ahead
whenever possible</b>, since you never know when circumstances beyond your control may conspire
to set you behind.  The video lectures for the entire semester are already available.</p>

<p><i>VIDEO LECTURES:</i> There are short video lectures, one or more for each
section.  I recommend (a) trying to watch them at higher speed (1.4x -- 2x) if they make sense, 
(b) rewinding to rewatch any parts you find confusing, and 
(c) watching them again later in the course to review (e.g., before exams). 

<p> <i>XIMERA:</i> Ximera provides an interactive platform for
  self-testing your understanding of the material.  There is one Ximera activity for each
  section/topic. These will only count as <b>extra credit</b>towards your participation
  grade since they are meant to be formative rather than summative.  </p>

<p> <i>PIAZZA:</i> The Piazza discussion board allows you to ask questions and interact with
one another (and the instructor) between class meetings. . We use Piazza because of its
excellent ability to include math notation using LaTeX/MathJax.  The quality and quantity of
your posts in Piazza count towards your participation grade.  If you don't have questions,
please try to help out your fellow students who might be confused.</p> 

<p> <i>PARTICIPATION:</i> Ximera, Piazza, asking good questions in class and working
productively in your groups all count towards your participation grade.</p>

<p> <i>WORKSHEETS:</i> Every section has a worksheet of basic problems, which you will be
working on collaboratively with others during classtime.  Worksheets are due a the start of
the following class.  These will be graded more for completion than for accuracy.  
</p>

<p> <i>HOMEWORK:</i> Recommended homework is assigned for 
each section, and is due in class on TUESDAY of the week following when that section is
covered.  The problems are grouped as
<i>Mandatory (Mand.)</i> and <i>Recommended (Rec.)</i>.  In order to be
well-prepared for exams you should be able to do all the homework problems.
As with the worksheets, solutions to these (for the 4th edition) will be released shortly 
afterwards, and they will be graded more for completion than accuracy. If you are using a
different edition of the text, a few of the numerical exercises may differ, but you can
ask on the discussion board what the correct answer is if you're really stuck after
looking at the solution.</p>  

<p> You may find some homework problems to be
challenging, leading you to spend lots of time working on them and
sometimes get frustrated.  This is natural.  I encourage you to work
with other people in person or electronically.  It's OK to get
significant help from any resource, but in the end, please write your
own solution in your own words.  <b>Copying someone else's work
without credit is plagiarism and will be dealt with according
to <a href="http://community.uconn.edu/the-student-code-appendix-a/">university
policy</a>.</b> Equally importantly, it is a poor learning strategy.

<p><i> LATE/UNREADABLE ASSIGNMENTS:</i>  Late homework and
worksheets will receive half credit if received by the next class period after they were
due, after that none.  
<!--  Homework and -->
<!--  worksheets that are not easily readable (e.g., because of poor scan quality for an upload) will not be -->
<!--  graded and will not receive credit. An app such as CamScanner on a smartphone can help -->
<!--  produce excellent PDF images of your work for uploading.  -->
</p> 

<p><i> ACADEMIC INTEGRITY:</i>  Please make sure you
  are familiar with and abide by
<a  href="http://community.uconn.edu/the-student-code-appendix-a/">The
  Student Code governing Academic Integrity in Undergraduate Education
  and Research.</a>  For quizzes and exams you may not discuss the
  material with anyone other than the instructor or offical proctor, and
  no calculators, phones, slide rules or other devices designed to aid
  communication or computation may be used unless otherwise specifically
  indicated on the exam.    
</p>

<p><i> CONTENT:</i> Linear Algebra is a beautiful and
important subject, rich in applications within mathematics and to many
other disciplines. For many of you this is the first course to begin bridging
  the gap between concrete computations and abstract reasoning.
  Understanding the notions of vector spaces, linear (in)dependence,
  dimension, and linear transformations will help you make sense of
  matrix manipulations at a deeper level, clarifying the underlying
  structure.  </p>

<p><i> APPLICATIONS:</i> This class may be your only chance to understand the theory of
  linear algebra, i.e., <b>why</b> things work the way they do.  In the future, this deeper
  understanding will be your key to harnessing the power of this subject to solve problems
  and shed light on your projects.  We need all the time we have to get to the most
  important tools, e.g., the <i>Singular Value Decomposition (SCD)</i>, leaving
  unfortunately little time to focus on applications.  The text has a sections on
  applications sprinkled throughout, and I encourage you to read them as you have time,
  during or after the term, particularly ones relevant to your current career path.</p>

<p> <i>ACCESSIBILITY &  DISABILITY ISSUES:</i> Please
  contact me and UConn's <a href="http://www.csd.uconn.edu/">Center for
  Students with Disabilities</a> as soon as possible if you have any
  accessibility issues, have a (documented) disability and wish to
  discuss academic accommodations, or if you would need assistance in
  the event of an emergency. </p>

<p><i> LEARNING:</i> <b> The only way to learn
mathematics is by doing it! </b> Complete each assignment to the best of
your ability, and get help when you are confused.  Take advantage of the online discussions
and office hours and the wealth of information on the web.   </p>

<center>
<table border="0" cellpadding="3" bgcolor="#DDDDDD">
<tbody>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr><th colspan="7" align="center"><span size="4" style="font-size: large;"><strong>2210Q LECTURE AND ASSIGNMENT SCHEDULE </strong></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr>
<td><span size="3" style="font-size: medium;"><strong>Section </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Due Date </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Topics </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Videos </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Ximera </strong></span></td>
<td><span size="3" style="font-size: medium;"><strong>HW (due following Tues.) </strong></span></td>
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§1.1</td>
<td>8/28 T</td>
<td>Intro to Linear Alg &amp; Systems of Eqns.</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/d3693532549b4020ad9c740c7517959c1d" target="_blank">E1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E1SysLinEqn.pdf">E1pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/78ba9210242b4a61befbdf0a321020a21d" target="_blank">E2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E2SolvLinSys.pdf">E2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA11/XA11" target="_blank">XA1.1</a></td>

<td><b>Mand: 3, 12, 21, 24, 25, 31. </b><br>Rec: 1, 2, 10, 13, 15, 16, 32. 
</tr>

<tr style="background-color: aqua;">
<td>§1.2</td>
<td>8/28 T</td>
<td>Row Reduction &amp; Echelon Forms</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/d2ea78d8934f4ace82b4613632ea6bf21d" target="_blank">E3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E3echelonForm.pdf">E3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/14de2bc27d2f4f9f8fd93b65cdbc72bd1d" target="_blank">E4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E4reducedEF.pdf">E4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA12/XA12" target="_blank">XA1.2</a></td>

<td><b>Mand: 2, 13, 19, 21, 24. </b><br>Rec: 10, 14, 29, 31. 
</tr>

<tr style="background-color: aqua;">
<td>§1.3</td>
<td>8/30 R</td>
<td>Vector Equations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/1992e569eb2e478daf339620c6ee41231d" target="_blank">E5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E5vecsLinComb.pdf">E5pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/6c59a3ed80fe4954ba3514dff912fd421d" target="_blank">Ov</a>, <a href="http://www.math.uconn.edu/~troby/VLpdfs/overviewSp17.pdf">Ovpdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA13/XA13" target="_blank">XA1.3</a></td>

<td><b>Mand: 6, 7, 15, 21, 23, 25. </b><br>Rec: 3, 9, 12, 14, 22.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§1.4</td>
<td>9/4 T</td>
<td>Matrix Equations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/bd862e8c40c743adbc54c6e6350f3d7c1d" target="_blank">E7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E7matrixVecEqns.pdf">E7pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/556a7ebe7d0847d097ff438992b5d65e1d" target="_blank">E8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E8mxEqnSpanSets.pdf">E8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA14/XA14" target="_blank">XA1.4</a></td>
<td><b>Mand: 1, 13, 17, 19, 22, 23, 25. </b><br>Rec: 4, 7, 9, 11, 31.
</tr>

<tr style="background-color: thistle;">
<td>§1.5</td>
<td>9/4 T</td>
<td>Solution Sets of Linear Systems</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/c2722b4af646425d9dd7033c3e093b6c1d" target="_blank">E9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E9solvHomogSys.pdf">E9pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/5d031432fb1c498eadf7ccd53cc01fd51d" target="_blank">E10</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E10solvGenSys.pdf">E10pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA15/XA15" target="_blank">XA1.5</a></td>
<td><b>Mand: 11, 15, 19, 23, 30, 32.</b><br>Rec: 2, 6, 18, 22, 27.
</tr>

<tr style="background-color: thistle;">
<td>§1.7</td>
<td>9/6 R</td>
<td>Linear Independence</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/56dd0274692a44bdadf817683dba735f1d" target="_blank">E11</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E11LinIndep.pdf">E11pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/468a60e79e004b528e2410922bf7981e1d" target="_blank">E12</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E12LinIndep2.pdf">E12pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA17/XA17" target="_blank">XA1.7</a></td>
<td><b>Mand: 1, 7, 15, 16, 20, 21. </b><br>Rec: 2, 5, 9, 32, 34, 35.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§1.8</td>
<td>9/11 T</td>
<td>Linear Transformations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/cf40116b4d504922a572109add6fd1521d" target="_blank">M2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M2LinTRansf.pdf">M2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA18/XA18" target="_blank">XA1.8</a></td>
<td><b>Mand: 2, 8, 9, 21, 31.</b><br>Rec: 4, 13, 15, 17.
</tr>

<tr style="background-color: aqua;">
<td>§1.9</td>
<td>9/11 T</td>
<td>Matrix of Linear Transformations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/3b02a4ff18ec4eb7ba37c28cc57dc1401d" target="_blank">M3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M3LinTransf2Thy.pdf">M3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/af4d1a9822f54594a642c9f6f76dbc7e1d" target="_blank">M4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M4LinTRansfPractice.pdf">M4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA19/XA19" target="_blank">XA1.9</a></td>
<td><b>Mand: 1, 8, 13, 19, 23, 26, 34. </b><br>Rec: 2, 7, 9, 15, 20, 32, 36.
</tr>

<tr style="background-color: aqua;">
<td>§2.1</td>
<td>9/13 R</td>
<td>Matrix Operations and Inverses</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/81c731662fd243a4bc6c31f7607b35ba1d" target="_blank">M5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M5mxOps.pdf">M5pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/f501b8c89eee4b009ad4a55e7b380ced1d" target="_blank">M6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M6mxOps2.pdf">M6pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA21/XA21" target="_blank">XA2.1</a></td>
<td><b>Mand: 5, 7, 10, 15. </b><br>Rec: 2, 18, 20, 22, 27, 28.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§2.2</td>
<td>9/18 T</td>
<td>Inverse of a Matrix</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/980d135dd77342f693ac9c92d3d9970b1d" target="_blank">M7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M7mxInversesDefEg.pdf">M7pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/22060b043bf84f7cab85cc2c448c28fc1d" target="_blank">M8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M8mxInvAlgElem.pdf">M8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA22/XA22" target="_blank">XA2.2</a></td>
<td><b>Mand: 9, 11, 15, 16, 29. </b><br>Rec: 3, 6, 7, 13, 23, 24, 32, 37.
</tr>

<tr style="background-color: thistle;">
<td>§2.3</td>
<td>9/18 T</td>
<td>Characterizations of Invertible Matrices</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/ec56df10c9db4b8f94180f1a13434bfa1d" target="_blank">M9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M9invertibleMxThm.pdf">M9pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA23/XA23" target="_blank">XA2.3</a></td>
<td><b>Mand: 11, 13, 15, 28. </b><br>Rec: 1, 3, 5, 8, 17, 26, 35.
</tr>

<tr style="background-color: thistle;">
<td>§3.1</td>
<td>9/20 R</td>
<td>Intro to Determinants</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/44f79da4c91c4709bc26f5022935e8b71d" target="_blank">D1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D1introDet.pdf">D1pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA31/XA31" target="_blank">XA3.1</a></td>
<td><b>Mand: 13, 20, 21, 37, 39. </b><br>Rec: 4, 8, 11, 31, 32.
</tr>

<tr style="background-color: thistle;">
<td>§3.2</td>
<td>9/20 R</td>
<td>Properties of Determinants</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/9be3c7b281114205825846b7436d2f4d1d" target="_blank">D2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D2detRowOps.pdf">D2pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/51ced837d31447828e4ab71f7fb132bc1d" target="_blank">D3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D3detColProd.pdf">D3pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA32/XA32" target="_blank">XA3.2</a></td>
<td><b>Mand: 8, 10, 16, 19, 27, 34. </b><br>Rec: 2, 3, 18, 20, 26, 32, 36, 40.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§1.1–2.5</td>
<td>9/25 T</td>
<td>Catchup &amp; Review Day</td>
<td> </td>
<td> </td>
<td><b>Do <a href="http://www.math.uconn.edu/~troby/math2210f18/Handouts/pm1F18Prob.pdf">Practice Midterm</a> by today!</b></td>
</tr>

<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: large;"> <strong> THURSDAY 27 September: FIRST MIDTERM EXAM (through §2.3)<br> <span color="red" style="color: red;">HW 3.1–3.2 due on Tues 10/2</span> </strong></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§3.3</td>
<td>10/2 T</td>
<td>Cramer's Rule and Volumes</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/420e2c5c5e1e4bf09421da8a53f531e21d" target="_blank">D4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/d4cramers.pdf">D4pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/d75c06b28c9e4431b636e28ae0dbb1d51d" target="_blank">D5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D5volume.pdf">D5pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA33/XA33" target="_blank">XA3.3</a></td>
<td><b>Mand: 6, 22, 23, 26. </b><br>Rec: 4, 5, 29, 30.
</tr>

<tr style="background-color: thistle;">
<td>§4.1</td>
<td>10/2 T</td>
<td>Vector Spaces &amp; Subspaces</td>
<td><a href="
https://mediasite.dl.uconn.edu/Mediasite/Play/f3427889ef3d484c8a866dd6497de2591d" target="_blank">B1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B1vecSpaces.pdf">B1pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/9cfebcc6653c4df0b596da13c1ffbbad1d" target="_blank">B2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B2vecSubspaces.pdf">B2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA41/XA41" target="_blank">XA4.1</a></td>
<td><b>Mand: 3, 8, 13, 23, 31. </b><br>Rec: 1, 12, 15, 17, 22, 32.
</tr>

<tr style="background-color: thistle;">
<td>§4.2</td>
<td>10/4 R</td>
<td>Null Spaces, Columns Spaces and Linear Transf.</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/adb301fd9a8848bcaea2290626b834b61d" target="_blank">B3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B3nullspace.pdf">B3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/5a8b0ea4646348c9b33b045b65a282841d" target="_blank">B4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B4colSpace.pdf">B4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA42/XA42" target="_blank">XA4.2</a></td>
<td><b>Mand: 11, 17, 25, 33, 34. </b><br>Rec: 3, 6, 14, 19, 21, 24, 32, 36.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§4.3</td>
<td>10/9 T</td>
<td>Bases and Linearly Independent Sets</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/8a63a8f199f94700b40b693c0934448b1d" target="_blank">B5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B5bases.pdf">B5pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/31449adac7fa48dcbe67fdeed90f2b8e1d" target="_blank">B6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B6basesNulCol.pdf">B6pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA43/XA43" target="_blank">XA4.3</a></td>
<td><b>Mand: 14, 21, 23, 29, 30. </b><br>Rec: 3, 4, 8, 10, 15, 24, 31.
</tr>

<tr style="background-color: aqua;">
<td>§4.4</td>
<td>10/9 T</td>
<td>Coordinate Systems</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/8740cc29d5594b6bbe12c24dcea204291d" target="_blank">B7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B7coordinates.pdf">B7pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/da8173b6b2a24b25b20f91c4df99ca2d1d" target="_blank">B8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B8coordIsom.pdf">B8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA44/XA44" target="_blank">XA4.4</a></td>
<td><b>Mand: 13, 15, 17, 21, 32. </b><br>Rec: 2, 3, 5, 7, 10, 11, 23.
</tr>

<tr style="background-color: aqua;">
<td>§4.5</td>
<td>10/11 R</td>
<td>Dimension of a Vector Space</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/e4c4b50655b649f399d0c229521c82d81d" target="_blank">B9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B9dimVS.pdf">B9pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/cfc6c046105b4c3aba4db15fa60b1b221d" target="_blank">B10</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B10dimSubspaces.pdf">B10pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA45/XA45" target="_blank">XA4.5</a></td>
<td><b>Mand: 8, 21, 23, 26, 29. </b><br>Rec: 1, 4, 11, 14, 28.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§4.6</td>
<td>10/16 T</td>
<td>Rank</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/74e48adf1c594cccb439fec32d23cd361d" target="_blank">B11</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B11rank.pdf">B11pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA46/XA46" target="_blank">XA4.6</a></td>
<td><b>Mand: 7, 17, 24, 27, 28. </b><br>Rec: 2, 5, 10, 13, 19.
</tr>

<tr style="background-color: thistle;">
<td>§4.7</td>
<td>10/16 T</td>
<td>Change of Basis</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/268c13d18d5b453bb80f88aecf3ac0e41d" target="_blank">B12</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B12ChangeBasis.pdf">B12pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA47/XA47" target="_blank">XA4.7</a></td>
<td><b>Mand: 3, 11, 13, 15. </b><br>Rec: 1, 5, 7, 9.
</tr>

<tr style="background-color: thistle;">
<td>§5.1</td>
<td>10/18 R</td>
<td>Eigenvectors &amp; Eigenvalues</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/524fe7b9d37e42c9ad77c6f3c8924bc61d
" target="_blank">F1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F1eigen.pdf">F1pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/97bdf293786640888623a6e8cde923391d" target="_blank">F2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F2GeomEigen.pdf">F2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA51/XA51" target="_blank">XA5.1</a></td>
<td><b>Mand: 2, 6, 13, 21, 23, 31. </b><br />Rec: 7, 11, 15, 19, 24, 25, 27. 
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§5.2</td>
<td>10/23 T</td>
<td>Characteristic Equation</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/f0e46c4ada36466980dbe274d307ae8e1d" target="_blank">F3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F3charEqn.pdf">F3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/0d786fbc404d4e129c8eac47926e3d9a1d" target="_blank">F4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F4Similarity.pdf">F4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA52/XA52" target="_blank">XA5.2</a></td>
<td><b>Mand: 9, 19, 21. </b><br>Rec: 2, 5, 12, 15, 20.
</tr>

<tr style="background-color: aqua;">
<td>§5.3</td>
<td>10/23 T</td>
<td>Diagonalization</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/434a2a8e772c49b6973de2f7c893520d1d" target="_blank">F5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F5diagonalization.pdf">F5pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA53/XA53" target="_blank">XA5.3</a></td>
<td><b>Mand: 11, 21, 24, 26. </b><br>Rec: 1, 4, 5, 9, 15, 17.
</tr>

<tr style="background-color: aqua;">
<td>§5.4</td>
<td>10/25 R</td>
<td>Eigenvectors &amp; Linear Transformations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/2f64b8a985d741c58e09ca7a77aa81f21d" target="_blank">F6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F6factoringLinTrans.pdf">F6pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA54/XA54" target="_blank">XA5.4</a></td>
<td><b>Mand: 6, 7, 10, 15, 25. </b><br>Rec: 1, 3, 16, 23.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§1.1–5.4</td>
<td>10/30 T</td>
<td>Catchup &amp; Review Day</td>
<td> </td>
<td> </td>
<td>Do <a href="http://www.math.uconn.edu/~troby/math2210f18/Handouts/pm2F18Prob.pdf">Practice Midterm 2</a> by today</td>
</tr>

<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: large;"> <strong> THURSDAY 1 NOVEMBER SECOND MIDTERM EXAM (through §5.4)<br> <span color="red" style="color: red;">HW 5.2–4 due on TUES 11/6.</span> </strong></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§6.1</td>
<td>11/6 T</td>
<td>Inner Product &amp; Orthogonality</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/c28965cfa5e6472a9b59f9db90dccd0e1d" target="_blank">G1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G1innerProd.pdf">G1pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA61/XA61" target="_blank">XA6.1</a></td>
<td><b>Mand: 3, 5, 19, 25, 27, 29. </b><br>Rec: 10, 16, 18, 23.
</tr>

<tr style="background-color: aqua;">
<td>§6.2</td>
<td>11/6 T</td>
<td>Orthogonal Sets</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/4b418facfe384c7f98e0429436148a4e1d" target="_blank">G2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G2orthoSetsSpaces.pdf">G2pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/b42e21fcd03a4f8696c7457ed68996681d" target="_blank">G3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G3orthonormality.pdf">G3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/10b8d7400df74f05ab4840e84bf996e21d" target="_blank">G4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G4orthoProj.pdf">G4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA62/XA62" target="_blank">XA6.2</a></td>
<td><b>Mand: 8, 14, 23, 27, 28, 29. </b><br>Rec: 3, 6, 9, 11, 20, 21, 26.
</tr>

<tr style="background-color: aqua;">
<td>§6.3</td>
<td>11/8 R</td>
<td>Orthogonal Projections</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/0fdbae8667df44c891f4e44b0e5377001d" target="_blank">G5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G5projApprox.pdf">G5pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA63/XA63" target="_blank">XA6.3</a></td>
<td><b>Mand: 1, 7, 17, 21, 24. </b><br>Rec: 6, 9, 11, 13, 23.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§6.4</td>
<td>11/13 T</td>
<td>Gram&ndash;Schmidt</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/a6fd13d067ea43b7a9e012e900918f431d" target="_blank">G6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G6gramSchmidt.pdf">G6pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/57e729953dc04f2baea1e0067f6e8bd01d" target="_blank">F7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F7qr.pdf">F7pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA64/XA64" target="_blank">XA6.4</a></td>
<td><b>Mand: 17, 19. </b><br>Rec: 1, 3, 7, 9, 11.
</tr>

<tr style="background-color: thistle;">
<td>§6.5</td>
<td>11/13 T</td>
<td>Least-Squares Problems</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/1ba687131e184d459b04b0accf204a631d" target="_blank">G7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G7leastSquares.pdf">G7pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA65/XA65" target="_blank">XA6.5</a></td>
<td><b>Mand: 3, 17, 19, 21. </b><br>Rec: 5, 7, 9, 11.
</tr>

<tr style="background-color: thistle;">
<td>§7.1</td>
<td>11/15 R</td>
<td>Diagonalization of Symmetric Matrices</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/c9db8ea6a3064bc1a82e905d7311b7ae1d" target="_blank">F8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F8diagSymmMxs.pdf">F8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA71/XA71" target="_blank">XA7.1</a></td>
<td><b>Mand: 1, 3, 5, 8, 13, 25. </b><br>Rec: 10, 17, 19, 29.
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: large;"> <strong> 18&ndash;24 NOVEMBER IS THANKSGIVING BREAK: NO CLASSES </strong></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
<td>§7.2</td>
<td>11/27 T</td>
<td>Quadratic Forms</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/774da9289c904bb68a1c61b8ee9a6acf1d" target="_blank">F9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F9quadForms.pdf">F9pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/7aab6ee2faee4bde8e4a252f908722dc1d" target="_blank">F10</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F10classifyingQF.pdf">F10pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA72/XA72" target="_blank">XA7.2</a></td>
<td><b>Mand: 8, 11, 21, 27. </b><br>Rec: 1, 5, 13, 19.
</tr>

<tr style="background-color: aqua;">
<td>§7.3</td>
<td>11/27 T</td>
<td>Constrained Optimization</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/e0a3b45c9b0447aeafcfaa34b344545b1d" target="_blank">F11</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F11ConstrOptQF.pdf">F11pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA73/XA73" target="_blank">XA7.3</a></td>
<td><b>Mand: 1, 3, 7, 11. </b><br>Rec: 5.
</tr>

<tr style="background-color: aqua;">
<td>§7.4</td>
<td>11/29 R</td>
<td>Singular Value Decomposition (SVD)</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/735f49e0e38d4392b76cb9b669b277001d" target="_blank">F12</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F12svdA.pdf">F12pdf</a>,
<!--  <td></td> --></td>
<td>No XA7.4</a></td>
<td><b>Mand: 3, 9, 17, 19. </b><br />Rec: 1, 11, 18. 
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr style="background-color: thistle;">
<td>§7.5</td>
<td>12/3 T</td>
<td>Principal Component Analysis (PCA)</td>
<td> </td>
<td>
<td><!--  <td> --></td>
<td> </td>
</tr>

<tr style="background-color: thistle;">
<td>§</td>
<td>12/5 R</td>
<td>Google PageRank and/or Review Day</td>
<td> </td>
<td> </td>
<td><!--  <td> --></td>
<td> </td>
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: large;"><span size="4" style="font-size: large;"> <strong> WEEK OF 11&ndash;17 DEC (TBD by Registrar): FINAL EXAM (through §7.4)<br></strong></span></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>
</tbody>
</table>
</center>


<p></p>


<HR>

<h3> Web Resources </h3>

<UL>
<LI> <a href="http://buzzard.ups.edu/">Rob Beezer</a> has
  a <a href="http://linear.ups.edu/">free open-source textbook</a> in
  linear algebra that uses the open-source software
  package <a href="http://sagemath.org">Sage</a> for computations.  You can
  download a print edition, or view
  the <a href="http://linear.ups.edu/html/fcla.html">online hyperlinked 
  version</a>.  (This text is geared a bit more for those transitioning to theoretical math
  courses.)  
  <br><br>
  
<li> <a href="http://web.mit.edu/18.06/www/"> The MIT 18.06 (Linear
Algebra) website </a> has lots of resources, including Mathlets (small
web-based teaching tools) (called "Demos" under
  the <a href="http://web.mit.edu/18.06/www/extras.shtml">Extras link</a>.).  
See also <a href="http://math.mit.edu/linearalgebra">resources related to
    Strang's standard textbook <i>Introduction to Linear Algebra</i></a>, in its 5th
  edition as of 2016. (This text is more geared towards applications.) 
<a href="http://math.mit.edu/~gs/">Strang's</a> video lectures are available on YouTube, or cataloged at
the <a href="https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/"> 
MIT 18.06 Course Website for Fall 2011</a>. 
  <br><br>


<LI> <a href="http://math.mercyhurst.edu/~lwilliams/Applets/algebra/linearTransformations.php">A
    Linear Transformation Viewer</a>
    by <a href="http://math.mercyhurst.edu/~lwilliams">Lauren K. Williams</a>.
<br><br>

<li> This is a brief <a href="http://www2.imm.dtu.dk/~pch/Projekter/Google.pdf">blurb on how Google
    ranks pages</a> when you give is a search query and 
a <a href="http://www.ams.org/samplings/feature-column/fcarc-pagerank"> 
more detailed accessible exposition</a>  from
the <a href="http://www.ams.org/samplings/samplings">AMS math samplings website</a>. 
  <br><br>

<!--  <li> <a -->
<!--  href="http://www.math.ucla.edu/~tao/resource/general/115a.3.02f/Gauss.html"> -->
<!--  A Gaussian Elimination (row reduction) applet from Terry Tao's website </a>   <br><br> -->

<!--  <li> <a href="http://maven.smith.edu/~patela/Applets/transf_index.html"> -->
<!--  A linear transformation applet for the plane from Smith College </a> -->
<!--    <br><br> -->

<!--  <li> Here's another <a href="http://www.cohomology.com/rref/"> Online -->
<!--  Row Reducer</a> from Greg Landwebber's <a -->
<!--  href="http://www.cohomology.com/">Cohomology.com</a> website.  -->
<!--    <br><br> -->

<li> An <a href="http://www.ams.org/samplings/feature-column/fcarc-svd"> elementary exposition of
  the singular value decomposition</a> from
the <a href="http://www.ams.org/samplings/samplings">AMS math samplings website</a>. 
  <br><br>

<LI> Here's
  an <a href="http://www.flashlightcreative.net/swf/mindreader/">Online
  Mind Reader</a>.  Can you figure out how it works?</LI> 
<!--Created by Andy Naughton; search for "online mind reader add digits,
  subtract" -->

</UL>


<!--  <HR> -->
<!--  <h3>Anonymous Feedback</h3> -->

<!--  <br> -->
<!--  Use this form to send me anonymous feedback or to answer the question: -->
<!--  <span style="font-weight: bold;">How can I improve your learning in -->
<!--  this class?</span>&nbsp; I will respond to any constructive suggestions -->
<!--  or comments in the space below the form.&nbsp;  -->
<!--  <\!-- You can also answer the question below:<br> -->
<!--  <br> -->
<!--  <center> -->
<!--  What's a good question for the midterm?<br> -->
<!--  </center> -\-> -->
<!--  <form id="MailForm" action="" -->
<!--        method="post" name="EMailSurvey"> -->
<!--    <input name="Subject" value="Math 2210Q Feedback Fall 2016" type="hidden"> <br> -->
<!--  <\!--  <label for="Message">Suggestions:</label><br> -\-> -->
<!--  <\!--  <pre><c></c><table align="center" cellpadding="4" cellspacing="4">  -->
<!--  <tbody><tr><td><br></td></tr></tbody></table><br><table align="center" cellpadding="0" cellspacing="4"><tbody><tr><td><br><textarea rows="8" cols="100" name="rap"></textarea> <br></td></tr></tbody></table><br></pre> -->
<!--    <table align="center" cellpadding="0" cellspacing="4"> -->
<!--      <tbody> -->
<!--        <tr> -->
<!--          <td> <input value="Send" type="submit"> </td> -->
<!--          <td><input value="Clear Form" type="reset"> </td> -->
<!--        </tr> -->
<!--      </tbody> -->
<!--    </table> -\-> -->
<!--  <center> -->
<!--    <textarea rows="8" cols="100" name="Message"></textarea> -->
<!--    <br> -->
<!--    <br> -->
<!--    <input value="Send" type="submit"> -->
<!--    <input value="Clear Form" type="reset"> -->
<!--  </center> -->
<!--  </form> -->
<!--  <br> -->

<!--  <h3> Feedback & Responses </h3> -->

<!--  <ol> -->


<!--  <LI>[Date] <i>This is a test.</i> <br> -->

<!--  <p class="mathpar">This is only a test.</p> </li> -->



<!--  </ol> -->


<HR>
<h2> NEWS, NOTES, AND HANDOUTS </h2>


<h3>Handouts</h3>

<p>
<UL>
<LI> <a href="~troby/math2210f18/Handouts/pq1.pdf">Practice Quiz #1</a></LI>
<!--  <LI> <a href="~troby/math2210f18/Handouts/pq1Soln.pdf">Practice Quiz #1 Solutions</a></LI> -->
<LI> <a href="~troby/math2210f18/Handouts/pm1F18Prob.pdf">Practice Midterm 1</a></LI>
<!--  <LI> <a href="~troby/math2210f18/Handouts/pm1F18Soln.pdf">Solutions to Practice Midterm 1</a></LI> -->
<!--  <LI> <a href="~troby/math2210f18/Handouts/pm2F18Prob.pdf">Practice Midterm 2</a></LI> -->
<!--  <LI> <a href="~troby/math2210f18/Handouts/pm2F18Soln.pdf">Solutions to Practice Midterm 2</a></LI> -->


<!--  <LI> <a href="~troby/math2210f18/Handouts/pfF18Prob.pdf">Practice Final</a></LI> -->

<!--  <LI> <a href="~troby/math2210f18/Handouts/pfF18Soln.pdf">Solutions to Practice Final</a></LI> -->

</UL>
</p>


<HR>
<p class="mathpar">Back to my <a href="~troby/index.html">home page</a>.<br> </>

</body>
</html>
