<title>Math 3160 Spring 2022 (Roby)</title>

<h3>
<span class="mathtitle"><a href="http://www2.math.uconn.edu/~troby/math3160s22/index.php"
target="_blank">Tom Roby's Math 3160 Home Page Spring 2022</a></span><br>
<span class="mathtitle">Applied Linear Algebra
</span> 
</h3>

<img class="mypic" ALIGN=right WIDTH=130 HEIGHT=200 HSPACE=50 src="http://www.math.uconn.edu/~troby/images/bestock09lant.jpg"> 


<h3>Questions or Comments?</h3>
<ul>

  <li><i>For questions about the <b>course material</b> or structure:</i> Please ask in the
  appropriate discussion forum in Zulip. (If you ask me such questions by email, I
  will redirect you there.) You can also talk to your classmates or me during class and
  right afterwards.  

  <li><i>For questions about using HuskyCT:</i> Once you are logged in to <a href="https://learn.uconn.edu/", target="_blank">HuskyCT</a>, click Student Help in the top bar.

   <li><i>For questions about enrollment, your individual circumstances, or suggestions for improving future versions of the
   course:</i> Please email me: <A HREF="mailto:tom.roby@uconn.eduTR">Tom
   Roby</A> (delete initials from end).  

  <li><i>My Homepage:</i> <a href="http://www.math.uconn.edu/~troby">
http://www.math.uconn.edu/~troby</a>
  <li> Office:  MONT 239; Phone:  860-486-8385 (no voicemail)<br> 
  <li>Office hours:  Mondays at 3:14 and by appointment at the following Zoom link:
    <a href="https://us02web.zoom.us/j/83656049211">https://us02web.zoom.us/j/83656049211</a>. 
  <!--  over Zoom, at the link:  -->
  <!--     <a href="https://us02web.zoom.us/j/83656049211">https://us02web.zoom.us/j/83656049211</a>. -->
  Feel free also to catch me right before or after class.  I am happy to schedule appointments
  by email, which I check frequently. 
</ul> 

</ul> 

<HR>


<h2>Class Information</h2>


<p class="mathpar"><i> COORDINATES:  </i>  Classes will meet Tuesdays and Thursdays
from 9:30&ndash;10:45 in MONT 320 (Section 003) <b>once in-person classes resume.  Until then, we will conduct classes
    over Zoom. A link will be sent by email and  available in HuskyCT to registered students.</b> 

<p><i> PREREQUISITES:</i> Calculus, up to and including series, limits, partial differentiation, and multiple
  integration, i.e.,  MATH 2110Q, 2130Q or 2143Q.</p> 

<p> <i> TEXT:</i> We will follow the UConn-developed Open Educational Resource <a href="https://probability.oer.math.uconn.edu/3160-oer/">UConn
    Undergraduate Probability OER</a>. Please <b>read ahead or watch video lectures for the week before coming to class</b>.  </p>

<p> <i> VIDEO LECTURES:</i> <a href="https://fractologist.github.io/">Joe Chen</a> and I developed
  a <a href="https://probability.oer.math.uconn.edu/3160-oer/video/">complete set of video lectures for the course</a>, 
  which you are welcome to use at any time.  I often recommend listening to them at slightly higher speed (say 1.5x),
  then stopping and maybe repeating any points you find difficult. Many students have found them helpful. <p> 

<p><i> WEB RESOURCES:</i> The homepage for this course will be available
and updated at  <a
href="http://www.math.uconn.edu/~troby/math3160s22">
http://www.math.uconn.edu/~troby/math3160s22</a>. 
<!--  The textbook author also has   a useful site with review sheets and downloadable data -->
<!--     <a href="http://wps.aw.com/aw_lay_linearalgebra_4">here</a>. -->
 </p>

<p><b><i>HuskyCT:</b></i> We will make limited use of HuskyCT, because of its many deficiencies.
I may post solutions to Quizzes there.  It now links to Gradescope, which is where you will turn in your HW.  
For classroom discussions, we will use Zulip (now that Piazza requires payment).  
</p>

<p><i> GRADING:</i>  Your grade will be based on two midterm exams, a final
exam, weekly quizzes, and homework, weighted as follows: 
<center>
<TABLE BORDER="4" CELLPADDING="2">
<tr><th> Midterm 1 <th> Midterm 2 <th> Final <th>  Quizzes <th> Homework <th>
<tr><th>15% <th>15% <th>30% <th>30% <th> 10% <th>
</TABLE>
</center>

 <p class="mathpar"><i> EXAMS: </i> The midterm dates are already scheduled (see below), so please mark your calendars 
now.  The final exam is scheduled by the registrar around mid-semester. 
No makeups will be given; instead if you have an approved reason for missing an exam, your other exams
will count for the appropriately higher percentage. 
If you miss the final for reasons <b>approved by the Dean of Students</b>, then you will have one chance to take a
make-up final exam in the second or third week of the following term.
I reserve the right to give a followup oral exam to verify your understanding if there are any questions about academic
integrity.</p> 

 <p class="mathpar"><i> QUIZZES: </i> Quizzes of about 10&ndash;15 minutes will be given each Tuesday (except midterm
 exam weeks), covering the previous week's material (at the level of HW exercises).
 There are no makeup quizzes; however, your lowest two quiz scores will be dropped. 

Here is a sample <a href="~troby/math3160s22/Handouts/pq1Prob.pdf">Practice Quiz</a> so you know ahead
 of time what the format will be. (Solutions will be provided below.) </p>


<p><i>STUDENT WORKFLOW:</i> For each week, you should 

<ol>
<li> Read the text or watch the video lectures ahead of time. 
<li> Attempt the exercises for the chapters covered. 
<li> Show up to class prepared to ask questions and go over problems;  we will keep class as active as possible. 
<li> Homework will be due the Sunday after we cover that chapter and is graded on completion, not accuracy.  Solutions are included in the
  text. 
<li> Use the ZULIP DISCUSSION BOARD, classroom interactions, and office hours <b>anytime</b> you get seriously stuck. 
<li> Be prepared for the QUIZ on the material the following Tuesday. 

</ol>

<p> This course will be <b>fast-paced</b> and cover quite a bit of material. Many students need this course to pass an
  actuarial exam, for which we cover the minimum syllabus.  
I strongly encourage you to <b>work ahead
whenever possible</b>, since you never know when circumstances beyond your control may conspire
to set you behind.  The video lectures for the entire semester are already available.</p>

<p> <i>ZULIP:</i> The Zulip discussion board allows you to ask questions and interact with
one another (and the instructor) between class meetings.  It is an open-source platform similar in feel to Slack.  We
  use Zulip because of its 
excellent ability to include math notation using LaTeX/MathJax.  The quality and quantity of
your posts in Zulip count towards your participation grade.  If you don't have questions,
please try to help out your fellow students who might be confused, or post a summary of the video lecture. </p> 

<p> <i>HOMEWORK:</i> Recommended homework is assigned for 
each chapter, and is due in HuskyCT/Gradescope by 11:59PM SUNDAY following the week that section is
covered. These are graded for completion, not accuracy. Solutions are available, but please attempt problems before you
  look at the solutions.  <b>Getting stuck and unstuck is a key learning strategy.</b> In order to be well-prepared for
  quizzes and exams you should be able to do all the homework problems. 
</p>  

<p> You may find some homework problems to be
challenging, leading you to spend lots of time working on them and
sometimes get frustrated.  This is natural.  I encourage you to work
with other people in person or electronically.  It's OK to get
significant help from any resource, but in the end, please write your
own solution in your own words.  <b>Copying someone else's work
without credit is plagiarism and will be dealt with according
to <a href="http://community.uconn.edu/the-student-code-appendix-a/">university
policy</a>.</b> Equally importantly, it is a poor learning strategy.

 <p><i> LATE/UNREADABLE ASSIGNMENTS:</i> Late homework and worksheets (up to 48 hours beyond the 2-hour grace
period) will receive half credit, after that none.  Homework and worksheets that are not easily readable
(e.g., because of bad photo quality) will not be graded and will not receive credit. Various smartphone
scanning apps can help produce very readable PDF images of your work. </p>

<!--  <p><i> LATE/UNREADABLE ASSIGNMENTS:</i>  Late homework and -->
<!--  worksheets will receive half credit if received by the next class period after they were -->
<!--  due, after that none.   -->
<!--  Homework and -->
<!--  worksheets that are not easily readable (e.g., because of poor scan quality for an upload) will not be -->
<!--  graded and will not receive credit. An app such as CamScanner on a smartphone can help -->
<!--  produce excellent PDF images of your work for uploading.  -->
</p> 


<!--  <p><i>SOFTWARE:</i> In most areas of mathematics it is -->
<!--    frequently helpful to use computer software not only for computations, -->
<!--    but also to explore examples, search for patterns, or test -->
<!--    conjectures.  For linear algebra there are several extensive -->
<!--    and sophisticated commercial software packages, including MATLAB, -->
<!--    Maple, and Mathematica.  Matlab is particularly good at linear -->
<!--    algebra for applications.  All of these can be expensive, depending on -->
<!--    your site license, but are <a href="http://software.uconn.edu/">currently -->
<!--    available to UConn students</a>.</p> -->

<!--  <p>An excellent alternative to the above is the free -->
<!--    open-source computer algebra -->
<!--    system <a href="http://www.sagemath.org">Sage</a>.  There are many -->
<!--    commands for linear algebra, and a textbook (linked below) has been -->
<!--    written that makes significant use of Sage examples.  Sage also -->
<!--    provides a full-fledged programming environment via the -->
<!--  <a href="http://en.wikipedia.org/wiki/Python_%28programming_language%29">Python -->
<!--    programming language</a>, but you don't need to be a programmer to use -->
<!--    it.  I highly recommend trying it out online, and installing a copy -->
<!--    on your computer.</p> -->

<p><i> ACADEMIC INTEGRITY:</i>  Please make sure you
  are familiar with and abide by
<a  href="http://community.uconn.edu/the-student-code-appendix-a/">The
  Student Code governing Academic Integrity in Undergraduate Education
  and Research.</a>  For exams you may not discuss the
  material with anyone other than the instructor or offical proctor, and
  no calculators, phones, slide rules or other devices designed to aid
  communication or computation may be used unless otherwise specifically
  indicated on the exam.    
</p>

<p><i> CONTENT:</i> Probability is a beautiful and important subject, rich in applications within mathematics and to
many other disciplines. It a foundation for understanding statistics, artificial intelligence and many aspects of life. 
 </p>

<p> <i>ACCESSIBILITY &  DISABILITY ISSUES:</i> Please
  contact me and UConn's <a href="http://www.csd.uconn.edu/">Center for
  Students with Disabilities</a> <b>as soon as possible (BUT NO LATER THAN END OF WEEK 2)</b> if you have any
  accessibility issues, have a (documented) disability and wish to
  discuss academic accommodations, or if you would need assistance in
  the event of an emergency. <b>In particular, CSD wants a great deal of lead time for scheduling exams</b>.</p>

<p><i> LEARNING:</i> <b> The only way to learn mathematics is by doing it! </b> Complete each assignment to the best of
your ability, and get help when you are confused.  Take advantage of the online discussions and office hours and the
wealth of information on the web. Especially for learning this subject, it is important to do lots of problems—many more
than I could reasonably assign you to hand in. Note that almost all problems are word problems, and careful attention to
language is imperative. </p>

<br>

<center>
<table border="0" cellpadding="3" bgcolor="#DDDDDD">
<tbody>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr><th colspan="7" align="center"><span size="4" style="font-size: large;"><strong>3160 LECTURE AND ASSIGNMENT SCHEDULE </strong></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr>
  <td><span size="3" style="font-size: medium;"><strong>Week </strong></span></td>
  <td><span size="3" style="font-size: medium;"><strong>Dates </strong></span></td>
  <td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Reading </strong></span></td>
  <td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Topics </strong></span></td>
  <td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Videos (optional) </strong></span></td>
  <td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Homework</strong></span></td>
  <td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>ETC</strong></span></td>
  <!--  <td><span size="3" style="font-size: medium;"><strong>HW (due following Fri.) </strong></span></td> -->
</tr>

<tr style="background-color: grey;">
  <td colspan="100%"> </td>
</tr>

<tr style="background-color: aqua;">
  <td style="text-align:center"><b>1</b>
  <td>1/18&ndash;21</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch1.pdf">Chapter 1</a></td>
  <td>Combinatorics: Permutations, Combinations, Binomial Coefficients</a></td>
   <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 01a, 01b, 01c</a></td>
  <td>All of §1.3 </td>
  <td><a href="~troby/math3160s22/Handouts/pq1Prob.pdf">Practice Quiz #1</a>
</tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>2</b>
   <td>1/24&ndash;29</td>
   <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch2.pdf">Chapter 2</a></td>
   <td>The probability setup</a></td>
  <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 02a, 02b</a></td>
   <td>All of §2.3 </td>
   <td>
</tr>

<tr style="background-color: aqua;">
  <td style="text-align:center"><b>3</b>
  <td>1/31&ndash;2/4</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch3.pdf">Chapter
    3</a> AND <a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch4.pdf">Chapter
    4</a> </td>
  <td>Independence &amp; Conditional Probability </a></td>
  <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lecture 3a</a> (Chapt. 3)
  AND <a href="http://probability.oer.math.uconn.edu/3160-oer/video/">3b and 3c</a> (Chapt. 4)</td> 
  <td>All of §3.3 &amp; §4.3 </td>
  <td>
</tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>4</b>
  <td>2/7&ndash;11</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch5.pdf">Chapter 5</a></td>
  <td>Random variables</td>
  <td> <a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 4a and 4b</a></td>
  <td>All of §5.3 </td>
  <td>
</tr>

<tr style="background-color: aqua;">
  <td style="text-align:center"><b>5</b>
  <td>2/14&ndash;18</td>
  <td><a href="https://probability.oer.math.uconn.edu/3160-oer/" class="external">Chapters 1&ndash;5</a></td>
  <td>REVIEW &amp; EXAM WEEK</a></td>
  <td></td> 
  <td></td>
</tr>
<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: arge;"> 
      <strong>THURSDAY 17 FEBRUARY: FIRST MIDTERM EXAM (Chapters 1&ndash;5) 
	<!--  <br> <span color="red" style="color: red;">HW 3.1–3.2 due on Tues 2/23</span> -->
       </strong></span></th></tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>6</b>
  <td>2/21&ndash;25</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch6.pdf">Chapter 6</a></td>
  <td>Some discrete Distributions </td>
  <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 4c and 4d</a> (Chapt. 6)</td> 
  <td>All of §6.3</td>
  <td>
</tr>

<tr style="background-color: aqua;">
  <td style="text-align:center"><b>7</b>
  <td>2/28&ndash;3/4</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch7.pdf">Chapter 7</a></td>
  <td>Continuous Distributions</td>
  <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lecture 5a (Chapt. 7)</a></td>
  <td>All of §7.3 </td>
  <td>
</tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>8</b>
   <td>3/7&ndash;3/11</td>
   <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch8.pdf">Chapter 8</a>
        AND <a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch9.pdf">Chapter 9</a></td>
   <td>Normal Distribution & Normal Approximations</td>
   <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 5b</a> (Chapt. 8&ndash;9)</td>
   <td>All of §8.3 &amp; §9.1 </td>
   <td>
</tr>

<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: large;"> <strong> 14&ndash;19 MARCH IS SPRING BREAK: NO CLASSES </strong></span></th></tr> --


<tr style="background-color: aqua;">
  <td style="text-align:center"><b>9</b>
  <td>3/21&ndash;25</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch10.pdf">Chapter 10</a></td>
  <td>Some continuous distributions</td>
  <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 5c and 5d</a> (Chapt. 10)</td>
  <td>All of §10.3 </td>
  <td>
</tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>10</b>
   <td>3/28&ndash;4/1</td>
   <td><a href="https://probability.oer.math.uconn.edu/3160-oer/" class="external">Chapters 1&ndash;5</a></td>
  <td>REVIEW &amp; EXAM WEEK</a></td>
  <td></td>
  <td></td> 
  <td></td>
</tr>
<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4" style="font-size: arge;"> 
      <strong>THURSDAY 31 MARCH: SECOND MIDTERM EXAM (Chapters 6&ndash;10) 
	<!--  <br> <span color="red" style="color: red;">HW 3.1–3.2 due on Tues 2/23</span> -->
       </strong></span></th></tr>

<tr style="background-color: aqua;">
  <td style="text-align:center"><b>11</b>
  <td>4/4&ndash;8</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch11.pdf">Chapter 11</a></td>
  <td>Multivariate Distributions</td>
  <td><a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 6a, 6b, 6c, 6d</a> (Chapt. 11)</td>
  <td>All of §11.7 </td>
  <td>
</tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>12</b>
   <td>4/11&ndash;15</td>
   <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch12.pdf">Chapter 12</a></td>
   <td>Expectation</td>
   <td><a href="https://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 7a, 7b, 7c</a> (Chapt. 12)</td>
   <td>All of §12.4 </td>
   <td>
</tr>

<tr style="background-color: aqua;">
  <td style="text-align:center"><b>13</b>
  <td>4/18&ndash;22</td>
  <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch13.pdf">Chapter 13</a></td>
  <td>Moment generating functions</td>
  <td><a href="https://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 7d and 7e</a> (Chapt. 13)</td>
  <td>All of §13.3 </td>
  <td>
</tr>

<tr style="background-color: thistle;">
  <td style="text-align:center"><b>14</b>
   <td>4/25&ndash;29</td>
   <td><a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch14.pdf">Chapter
   14</a> AND <a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch15.pdf">Chapter
   15</a></td>
   <td>Limit laws, modes of convergence, and Inequalities</td>
   <td><a href="https://probability.oer.math.uconn.edu/3160-oer/video/"></a> <a href="http://probability.oer.math.uconn.edu/3160-oer/video/">Video Lectures 8a and 8b</a> (Chapt. 14)</td>
   <td>All of §14.4 </td>
   <td>
</tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>

<tr><th colspan="7" align="center" style="background-color: lightgreen;"><span size="4"
style="font-size: large;"><span size="4" style="font-size: large;"> <strong> 
TUESDAY 3 MAY, 08:00-10:00: FINAL EXAM (covers entire course)<br></strong></span></span></th></tr>

<tr style="background-color: grey;">
<td colspan="100%"> </td>
</tr>
</tbody>
</table>
</center>


<p></p>


<HR>

<h3> Web Resources </h3>

<UL>
<LI> Here's a free online 
<a href="http://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/amsbook.mac.pdf">
Introduction to Probability</a>, coauthored by one of my professors at Swarthmore.</LI>  

  <LI> The videos and animations available through <a href="https://www.3blue1brown.com/">3Blue1Brown</a> are highly
  recommended (not just for linear algebra). <br><br></LI>
  <LI> WEEK 3: Try to solve
  this <a href="https://probability.oer.math.uconn.edu/2020/09/12/probability-in-riddler-express-from-fivethirtyeight/">optional
      pickup basketball riddle</a>.</LI>
  <LI><a href="https://iwant2study.org/lookangejss/math/ejss_model_GaltonBoardwee/GaltonBoardwee_Simulation.xhtml">Galton
  Board Simulation</a> of balls falling randomly to form the normal curve, formalized
  in <a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch9.pdf">Chapter
  9</a> and <a href="https://probability.oer.math.uconn.edu/wp-content/uploads/sites/2187/2018/01/prob3160ch14.pdf">Chapter 14</a>
  <LI> MORE TO COME... </LI>
  
<LI> Here's
  an <a href="https://mindreader.hacktest.net/en/">Online
  Mind Reader</a>.  Can you figure out how it works?</LI> 
<!--Created by Andy Naughton; search for "online mind reader add digits,
  subtract" -->

</UL>




<HR>
<h2> NEWS, NOTES, AND HANDOUTS </h2>


<h3>Handouts</h3>

<p>
<UL>
<LI> <a href="~troby/math3160s22/Handouts/pq1Prob.pdf">Practice Quiz #1</a></LI>
<LI> <a href="~troby/math3160s22/Handouts/pq1Soln.pdf">Practice Quiz #1 Solutions</a></LI>

<!--  <LI> <a href="~troby/math3160s22/Handouts/pm1F19Prob.pdf">Practice Midterm 1</a></LI> -->
<!--  <LI> <a href="~troby/math3160s22/Handouts/pm1F19Soln.pdf">Solutions to Practice Midterm 1</a></LI> -->
<!--  <LI> <a href="~troby/math3160s22/Handouts/pm2F19Prob.pdf">Practice Midterm 2</a></LI> -->
<!--  <LI> <a href="~troby/math3160s22/Handouts/pm2F19Soln.pdf">Solutions to Practice Midterm 2</a></LI> -->


<!--  <LI> <a href="~troby/math3160s22/Handouts/pfF19Prob.pdf">Practice Final</a></LI> -->

<!--  <LI> <a href="~troby/math3160s22/Handouts/pfF19Soln.pdf">Solutions to Practice Final</a></LI> -->

</UL>
</p>


<HR>
<p class="mathpar">Back to my <a href="http://www.math.uconn.edu/~troby">home page</a>.<br> </>

</body>
</html>
