
<title>Math 2210 Summer 2021 (Roby)</title>

<h3>
<span class="mathtitle"><a href="http://www2.math.uconn.edu/~troby/math2210sum21/index.php" target="_blank">Tom Roby's Math 2210Q Home Page (Summer 2021)</a></span><br>
<span class="mathtitle">Applied Linear Algebra</span>
 <h2><b><i><p style="color:#FF0000";>See <span style="color:blue;">UPDATED</span> ONLINE EXAM and COURSE PACE notes (in Red) below!</p></i></b></h2>

</h3>

<img class="mypic" ALIGN=right WIDTH=130 HEIGHT=200 HSPACE=50 src="http://www2.math.uconn.edu/~troby/images/bestock09lant.jpg"> 


<h3>Questions or Comments?</h3>
<ul>

  <li><i>For questions about the <b>course material</b> or structure:</i> Please ask in the
  approriate discussion forum in Zulip. 

  <li><i>For questions about using HuskyCT:</i> Once you are logged in to <a href="https://learn.uconn.edu/",
  target="_blank">HuskyCT</a>, look for <b>Tech Help</b> under <b>Resources</b> in the left menu bar.  

  <li><i>For questions about assignment grades:</i> Please email the TA managing grades for the course: <b>TBD</b>
<!--  <A HREF="mailto:matthew.plante@uconn.edu">Matthew Plante</a>.  -->

   <li><i>For questions about enrollment or suggestions for improving future versions of the
   course:</i> Please email the Professor: <A HREF="mailto:tom.roby@uconn.eduTR">Tom
   Roby</A> (delete initials from end).  

  <li><i>Professor's Homepage:</i> <a href="http://www2.math.uconn.edu/~troby" target="_blank">
http://www2.math.uconn.edu/~troby</a>
  <li><i>Office hours</i>: Office hours will be held online.  Times and 
  online platform are announced on theH uskyCT course home page.  
  <!--  If there is sufficient interest, there may also be some on-campus office hours as well.  -->
  We are also happy to respond to questions and comments within the Zulip discussion forum, which we check
  regularly.   
</ul> 

<HR>


<h2>Class Information</h2>

<p><i>INSTRUCTIONAL TEAM:</i>  
<ul>
<li><i>Lead Instructor:</i> <a href="http://www2.math.uconn.edu/~troby" target="_blank">Tom Roby</a>; 
<li><i>Teaching Assistants:</i> TBD
<!--  <li><i>Teaching Assistant:</i> <A HREF="mailto:noah.hughes@uconn.edu">Noah Hughes</a>; -->
<!--  <li><i>Teaching Assistant:</i> <A HREF="mailto:matthew.plante@uconn.edu">Matthew Plante</a>; -->
<!--  <li><i>Teaching Assistant:</i> <A HREF="mailto:gianmarco.molino@uconn.edu">Gianmarco Molino</a>; -->
</ul>
<p><i> COORDINATES:</i>  Classes meet online, and you can find everything
you need linked within Husky CT.  

<p><i> PREREQUISITES:</i> MATH 1132 (Calculus II), 1152 (Honors Calculus
  II), OR 2142 (Advanced Calculus II).</p> 

<p> <i> TEXT:</i> You will need to obtain a copy of the textbook, which is 
David C. Lay's
textbook 
<i>Linear Algebra and Its Applications</i></a>.  Any edition you can find from the 3rd on
should be fine for this class, except that the problem numbers may vary slightly. I recommend any version that
you can get cheaply.  <b>You do not need any special access code</b> (despite what the UConn bookstore may say).  The
homework solutions are written for the <b>4th Ed.</b>; a few of the numerical
problems have different numbers, and a few of the theoretical problems have different problem numbers.  

<p><i> WEB RESOURCES:</i>   <b> (1)</b> For overall course information, this website (that you are on): 
  <a href="http://www2.math.uconn.edu/~troby/math2210sum21" target="_blank">
    http://www2.math.uconn.edu/~troby/math2210sum21</a> 
has static information about the course, with links to many of the course materials. <br>
  <b> (2) </b>A version of the schedule on the HuskyCT site will be updated with homework and worksheet solutions.</br>
  <b> (3) </b>The class discussion board (Zulip) will include announcements, practice exams, and other information. </br>
  <b> (4) </b>Links to additional web resources are posted below the schedule. 
</p>

<p><i>SOFTWARE:</i> In most areas of mathematics it is
  frequently helpful to use computer software not only for computations,
  but also to explore examples, search for patterns, or test
  conjectures.  For linear algebra there are several extensive
  and sophisticated commercial software packages, including MATLAB,
  Maple, and Mathematica.  Matlab is particularly good at linear
  algebra for applications.  All of these can be expensive, depending on
  your site license, but are 
<a href="http://software.uconn.edu" target="_blank">currently
  available to UConn students</a>.</p>

<p>An excellent alternative to the above is the free
  open-source computer algebra
  system <a href="http://www.sagemath.org" target="_blank">Sage</a>.  There are many
  commands for linear algebra, and Beezer's textbook (linked above) has been
  written that makes significant use of Sage examples.  Sage also
  provides a full-fledged programming environment via the
<a href="http://en.wikipedia.org/wiki/Python_%28programming_language%29">Python
  programming language</a>, but you don't need to be a programmer to use
  it.  I highly recommend trying it out online, and installing a copy
  on your computer.</p>

<p><i> GRADING:</i>  Your grade will be based on two midterm exams, a final
exam, worksheets, homework and participation. </p>

The breakdown of points is:<br> <br>

<center>
<TABLE BORDER="4" CELLPADDING="2">
<tr><th> Midterms <th> Final <th> Worksheets  <th> Homework <th> Participation </tr>
<tr><th>20% each <th>30% <th>10% <th> 8% <th>12% </tr>
</TABLE>
</center>
<p></p>

<p style="color:#FF0000";><i>EXAMS:</i> 
Because of the pandemic, exams will be administered <b>online,</b> probably over the Zoom platform.  
But you must take your exams with a <b>webcam</b> and <b>decent internet connectivity</b> that
  allows us to see you continuously during the exam administration.  We also plan to do some short follow-up oral
  examinations to check your understanding in case there are any concerns (e.g., your internet goes out during the exam
  administration, you have problems uploading files, etc.).</p> 

<!--  <del>All exams will be <b>in-person</b> and <b>proctored on campus</b>. </del>   -->

<p style="color:#FF0000";>The dates are already scheduled (see below), so please mark your
calendars now.  All exams (like math itself at this level)
are cumulative. No makeups will be given; instead if you have an approved reason for missing
an exam, the final will count for the appropriately higher percentage. If you miss the final
for reasons <b>approved by the Dean of Students</b>, then you will have one chance to take a
make-up final exam in early September. </p>

<!--  <del><p style="color:#FF0000";>ALL STUDENTS WILL BE -->
<!--  REQUIRED TO TAKE AN IN-PERSON FINAL ON THE STORRS CAMPUS, EITHER ON THE LAST DAY OF THE -->
<!--  SESSION OR THE OFFICAL MAKEUP DAY (3rd week of the Fall term).  YOU MUST GET AT LEAST 60% ON -->
<!--  THE FINAL TO PASS THE CLASS.  NO EXCEPTIONS!</p></del> -->


<p><i>STUDENT WORKFLOW:</i> In the course schedule, each section in the text has a single
line indicating the topic, which may correspond to multiple video lectures. For each section
you should:

<ol>
<li> WATCH the VIDEO LECTURE(S) & take notes (pdfs of slides are available);
<li> DO the XIMERA ACTIVITIES as a self check;
<li> DO the WORKSHEET problems and SUBMIT them by the deadline on the schedule;
<li> USE the ZULIP message board or ask in  <b>anytime</b> you get seriously stuck;
<li> CHECK your WORKSHEET against the solutions (posted the morning after the due date);
<li> READ the TEXTBOOK to fill in gaps, see an alternate presentation, straighten out
confusing points; 
<li> DO as many HW problems as you can, and SUBMIT them the day AFTER the worksheet is due;
<li> CHECK your HW against the solutions (posted the morning after the due date);
</ol>
</p>

<p style="color:#FF0000";>Note that many days have multiple sections due.  This course will be <b>fast-paced</b> and cover
the <i>full semester's worth of material</i>.  Please make sure you clear your calendar to
allow adequate time for all the activities and for the material to sink in.  If you have a
full-time job, plan to have no social life.   
I strongly encourage you to <b>work ahead whenever possible</b>, 
since you never know when circumstances beyond your control may conspire
to set you behind.  Catch-up time is much more limited than during a regular term.  
</p>

<p><i>VIDEO LECTURES:</i> There are short video lectures, one or more for each
section.  I recommend (a) trying to watch them at higher speed (1.4x&ndash;2x) if they make sense, 
(b) rewinding to rewatch any parts you find confusing, and (c) watching them again later in
the course to review (e.g., before exams). 

<p> <i>XIMERA:</i> Ximera provides an interactive platform for
  self-testing your understanding of the material.  There is one Ximera activity for each
  section/topic. These will only count towards your participation grade since they are meant
  to be formative rather than summative.</p>

<p> <i>ZULIP:</i> The Zulip discussion board is what makes this class a community since we do not meet in
person. We use Zulip because of its excellent ability to include math notation using LaTeX/MathJax.  The
quality and quantity of your posts in Zulip count towards your participation grade.  If you don't have
questions, please try to help out your fellow students who might be confused.</p>

<p> <i>DISCUSSION SECTIONS:</i>We will survey student availability on the first day and try to create <i>discussion
    sections</i> for small groups to meet via videoconferencing.  Attending these <b>will count towards your
    participation grade</b>.  Here you can get your questions answered, or watch the instructors go over
    problems. 

<p> <i>PARTICIPATION:</i> Your participation grade will be a linear combination (with positive coefficients) 
of your: <b> (1)</b> completed Ximera activities,  <b> (2)</b> responding to class surveys,  AND your <b> (3)</b> attendance at
  discussion sections or <b> (4)</b>  posts on Zulip (at least a couple each week if you aren't attending
  discussions).</p>  

<p> <i>WORKSHEETS:</i> Every section has a worksheet of basic problems.  Attempt these as soon as you're
ready, and upload your written solutions in HuskyCT (as a readable PDF file) by 11:59PM on the due date.
(Generally if a submission arrives no more than 2 hours late, we will count it as "on time".)  Solutions to
these will be released shortly afterwards.  These will be graded for completion rather than accuracy.
<br><br>

<i><b>IMPORTANT:</b> HuskyCT does not handle other image formats as well as PDF, so please make sure you
upload a <b>SINGLE PDF</b> file for each assignment.  There are free apps (e.g., "CamScanner") that allow you to take a
  picture with a smart phone that is immediately converted to PDF.</i> </p>

<p> <i>HOMEWORK:</i> Homework is assigned for each section, and is due one day AFTER the corresponding
worksheet (again uploaded as a <b> SINGLE PDF</b> by 11:59PM, with a 2-hour grace period).  The problems are grouped as
<i>Mandatory (Mand.)</i> and <i>Recommended (Rec.)</i>.  As with the worksheets, solutions to these will be
released shortly afterwards, and they will be graded for completion rather than accuracy.  In order to be
well-prepared for exams you should be able to do all the homework problems.</p>

<p> You may find some homework problems to be challenging, leading you to spend lots of time working on them and
sometimes get frustrated.  This is natural.  I encourage you to work with other people. It's OK to get significant help
from any resource, but in the end, please write your own solution in your own words.  <b>Copying someone else's work
without credit is plagiarism and will be dealt with according
to <a href="http://community.uconn.edu/the-student-code-appendix-a/" target="_blank">university policy</a>.</b>  Equally
importantly, it is a poor learning strategy.

<p><i> LATE/UNREADABLE ASSIGNMENTS:</i> Late homework and worksheets (up to 24 hours beyond the 2-hour grace
period) will receive half credit, after that none.  Homework and worksheets that are not easily readable
(e.g., because of bad image quality) will not be graded and will receive no credit. </p>

<p><i> ACADEMIC INTEGRITY:</i> Please make sure you are familiar with and abide by <a
  href="http://community.uconn.edu/the-student-code-appendix-a/" target="_blank">The Student Code governing Academic Integrity
  in Undergraduate Education and Research.</a> For exams you may not discuss the material with anyone other
  than the instructor or offical proctor, and no calculators, phones, slide rules or other devices designed to
  aid communication or computation may be used unless otherwise specifically indicated on the exam.  </p>

<p><i> CONTENT:</i> Linear Algebra is a beautiful and important subject, rich in applications within
mathematics and to many other disciplines. For many of you this is the first course to begin bridging the gap
between concrete computations and abstract reasoning.  Understanding the notions of vector spaces, linear
(in)dependence, dimension, and linear transformations will help you make sense of matrix manipulations at a
deeper level, clarifying the underlying structure.  </p>

<p> <i>ACCESSIBILITY & DISABILITY ISSUES:</i> Please contact me and UConn's <a
  href="http://www.csd.uconn.edu/" target="_blank">Center for Students with Disabilities</a> as soon as possible if you have
  any accessibility issues, have a (documented) disability and wish to discuss academic accommodations, or if
  you would need assistance in the event of an emergency. </p>

<p><i> LEARNING:</i> <b> The only way to learn
mathematics is by doing it! </b> Complete each assignment to the best of
your ability, and get help when you are confused.  Take advantage of the online discussions
and office hours and the wealth of information on the web.   </p>


<center>
<table border="0" cellpadding="3" bgcolor="#DDDDDD">
<tbody>
<tr style="background-color: grey;"><td colspan="100%"></td></tr>

<tr><th colspan="7" align="center"><span size="4" style="font-size: large;"><strong>2210Q LECTURE AND ASSIGNMENT SCHEDULE </strong></span></th></tr>
<tr style="background-color: grey;"><td colspan="100%"></td></tr>

<!--  <tr><th colspan="7" align="center"> </th></tr> -->
<tr>
<td><span size="3" style="font-size: medium;"><strong>Section </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Due Date </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Topics </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Videos </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Ximera </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Worksheet </strong></span></td>
<td><span size="3" style="font-size: medium;"><strong>Homework (due next day)</strong></span></td>
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 1 </strong></FONT></th></tr>


<tr style="background-color: aqua;">
<td>&sect;1.1</td>
<td>6/1 Tu</td>
<td>Intro to Linear Alg &amp; Systems of Eqns.</a></td>
<td><a href="https://www.youtube.com/watch?v=0PloaPk86H0&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=1" target="_blank">E1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E1SysLinEqn.pdf" target="_blank">E1pdf</a>, <a href="https://www.youtube.com/watch?v=7QvN1bIMSZQ&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=2" target="_blank">E2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E2SolvLinSys.pdf" target="_blank">E2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA11/XA11", target="_blank">XA1.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7649910_1", target="_blank">W1.1</a>
<td><b>Mand: 3, 12, 21, 24, 25, 31. </b><br>Rec: 1, 2, 10, 13, 15, 16, 32. 
</tr>

<tr style="background-color: aqua;">
<td>&sect;1.2</td>
<td>6/1 Tu</td>
<td>Row Reduction & Echelon Forms</td>
<td><a href="https://www.youtube.com/watch?v=S_-cHRG0qeA&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=3" target="_blank">E3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E3echelonForm.pdf" target="_blank">E3pdf</a>, <a href="https://www.youtube.com/watch?v=qP2bNBSMWF4&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=4" target="_blank">E4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E4reducedEF.pdf" target="_blank">E4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA12/XA12", target="_blank">XA1.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7714627_1", target="_blank">W1.2</a>
</td>
<td><b>Mand: 2, 13, 19, 21, 24. </b><br>Rec: 10, 14, 29, 31. 
</tr>

<tr style="background-color: thistle;">
<td>&sect;1.3</td>
<td>6/2 We</td>
<td>Vector Equations</td>
<td><a href="https://www.youtube.com/watch?v=Bj6HJ2qDrO4&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=5" target="_blank">E5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E5vecsLinComb.pdf" target="_blank">E5pdf</a>, <a href="https://www.youtube.com/watch?v=QX1tfnX6-Eg&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=1&t=2s" target="_blank">Ov</a>, <a href="http://www.math.uconn.edu/~troby/VLpdfs/overviewSp17.pdf" target="_blank">Ovpdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA13/XA13", target="_blank">XA1.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7714628_1", target="_blank">W1.3</a>
<td><b>Mand: 6, 7, 15, 21, 23, 25. </b><br>Rec: 3, 9, 12, 14, 22.
</tr>

<tr style="background-color: aqua;">
<td>&sect;1.4</td>
<td>6/3 Th</td>
<td>Matrix Equations</td>
<td><a href="https://www.youtube.com/watch?v=bTGS_T3DWGI&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=6" target="_blank">E7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E7matrixVecEqns.pdf" target="_blank">E7pdf</a>, <a href="https://www.youtube.com/watch?v=mTuv_veJYmE&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=7" target="_blank">E8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E8mxEqnSpanSets.pdf" target="_blank">E8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA14/XA14", target="_blank">XA1.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653879_1", target="_blank">W1.4</a>
<td><b>Mand: 1, 13, 17, 19, 22, 23, 25. </b><br>Rec: 4, 7, 9, 11, 31.
</tr>

<tr style="background-color: aqua;">
<td>&sect;1.5</td>
<td>6/3 Th</td>
<td>Solution Sets of Linear Systems</td>
<td><a href="https://www.youtube.com/watch?v=odtIy_u1moA&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=8" target="_blank">E9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E9solvHomogSys.pdf" target="_blank">E9pdf</a>, <a href="https://www.youtube.com/watch?v=l8pHK63xnPk&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=9" target="_blank">E10</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E10solvGenSys.pdf" target="_blank">E10pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA15/XA15", target="_blank">XA1.5</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653853_1", target="_blank">W1.5</a>
<td><b>Mand: 11, 15, 19, 23, 30, 32.</b><br>Rec: 2, 6, 18, 22, 27.
</tr>

<tr style="background-color: thistle;">
<td>&sect;1.7</td>
<td>6/5 Sa</td>
<td>Linear Independence</td>
<td><a href="https://www.youtube.com/watch?v=erjhxHnbglc&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=10" target="_blank">E11</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E11LinIndep.pdf" target="_blank">E11pdf</a>, <a href="https://www.youtube.com/watch?v=53Qyto-tKUU&list=PLCyMqkq53VeSogd_0OQtljaVxBtZ0xAC2&index=11" target="_blank">E12</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/E12LinIndep2.pdf" target="_blank">E12pdf</a>,</td>
<td><a href="https://ximera.osu.edu/UConnLinAlg/XA17/XA17" target="_blank">XA1.7</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7784384_1", target="_blank">W1.7</a> 
<td><b>Mand: 1, 7, 15, 16, 20, 21. </b><br>Rec: 2, 5, 9, 32, 34, 35.
</tr>
<tr style="background-color: thistle;">
<td>&sect;1.8</td>
<td>6/5 Sa</td>
<td>Linear Transformations</td>
<td><a href="https://www.youtube.com/watch?v=W1OMSpcEFds&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=1" target="_blank">M2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M2LinTRansf.pdf" target="_blank">M2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA18/XA18", target="_blank">XA1.8</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7799321_1", target="_blank">W1.8</a> 
<td><b>Mand: 2, 8, 9, 21, 31.</b><br>Rec: 4, 13, 15, 17.
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 2 </strong></FONT></th></tr>


<tr style="background-color: thistle;">
<td>&sect;1.9</td>
<td>6/7 Mo</td>
<td>Matrix of Linear Transformations</td>
<td><a href="https://www.youtube.com/watch?v=2KyK3WVqonA&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=2" target="_blank">M3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M3LinTransf2Thy.pdf" target="_blank">M3pdf</a>, 
<a href="https://www.youtube.com/watch?v=twJQxX7tqq0&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=4" target="_blank">M4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M4LinTRansfPractice.pdf" target="_blank">M4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA19/XA19", target="_blank">XA1.9</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653855_1", target="_blank">W1.9</a>
<td><b>Mand: 1, 8, 13, 19, 23, 26, 34. </b><br>Rec: 2, 7, 9, 15, 20, 32, 36.
</tr>


<tr style="background-color: thistle;">
<td>&sect;2.1</td>
<td>6/7 Mo</td>
<td>Matrix Operations and Inverses</td>
<td><a href="https://www.youtube.com/watch?v=a2JexxDn12o&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=5" target="_blank">M5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M5mxOps.pdf" target="_blank">M5pdf</a>, <a href="https://www.youtube.com/watch?v=a2JexxDn12o&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=5" target="_blank">M6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M6mxOps2.pdf" target="_blank">M6pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA21/XA21", target="_blank">XA2.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653874_1", target="_blank">W2.1</a>
<td><b>Mand: 5, 7, 10, 15. </b><br>Rec: 2, 18, 20, 22, 27, 28.
</tr>

<tr style="background-color: aqua;">
<td>&sect;2.2</td>
<td>6/8 Tu</td>
<td>Inverse of a Matrix</td>
<td><a href="https://www.youtube.com/watch?v=K76XsB14lSA&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=6" target="_blank">M7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M7mxInversesDefEg.pdf" target="_blank">M7pdf</a>, <a href="https://www.youtube.com/watch?v=6b0EX-2UWn4&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=7" target="_blank">M8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M8mxInvAlgElem.pdf" target="_blank">M8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA22/XA22", target="_blank">XA2.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7834059_1", target="_blank">W2.2</a>
<td><b>Mand: 9, 11, 15, 16, 29. </b><br>Rec: 3, 6, 7, 13, 23, 24, 32, 37.
</tr>

<tr style="background-color: thistle;">
<td>&sect;2.3</td>
<td>6/9 We</td>
<td>Characterizations of Invertible Matrices</td>
<td><a href="https://www.youtube.com/watch?v=92-HVreKnWI&list=PLCyMqkq53VeSK_cXrAN-vwu2OWdl17shW&index=8" target="_blank">M9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/M9invertibleMxThm.pdf" target="_blank">M9pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA23/XA23", target="_blank">XA2.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7834060_1", target="_blank">W2.3</a> 
<td><b>Mand: 11, 13, 15, 28. </b><br>Rec: 1, 3, 5, 8, 17, 26, 35.
</tr>

<tr style="background-color: aqua;">
<td>§1.1–2.3</td>
<td>6/10 Th</td>
<td>Catchup &amp; Review Day</td>
<td> </td>
<td> </td>
<td> </td>
<td><b>Do Practice Midterm by today!</b></td>
</tr>

<tr><th style="background-color: lightgreen;" colspan=7 align="center"><font size=4>
<strong> FRIDAY 11 JUNE: FIRST MIDTERM EXAM (through &sect;2.3)<br>
   <font color="red"> Tentatively 8:00PM&ndash;10:00PM</font></strong></FONT></th></tr>


<tr style="background-color: thistle;">
<td>&sect;3.1</td>
<td>6/13 Su</td>
<td>Intro to Determinants</td>
<td><a href="https://www.youtube.com/watch?v=l6rACB8Vvc4&list=PLCyMqkq53VeSk8M3Y6ybj8UvZwld__6a6&index=1" target="_blank">D1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D1introDet.pdf" target="_blank">D1pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA31/XA31", target="_blank">XA3.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8023531_1", target="_blank">W3.1</a>
<td><b>Mand: 13, 20, 21, 37, 39. </b><br>Rec: 4, 8, 11, 31, 32.
</tr>

<tr style="background-color: thistle;">
<td>&sect;3.2</td>
<td>6/13 Su</td>
<td>Properties of Determinants</td>
<td><a href="https://www.youtube.com/watch?v=-V5sDyvHBh4&list=PLCyMqkq53VeSk8M3Y6ybj8UvZwld__6a6&index=2" target="_blank">D2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D2detRowOps.pdf" target="_blank">D2pdf</a>, <a href="https://www.youtube.com/watch?v=Vq9dnevRyto&list=PLCyMqkq53VeSk8M3Y6ybj8UvZwld__6a6&index=3" target="_blank">D3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D3detColProd.pdf" target="_blank">D3pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA32/XA32", target="_blank">XA3.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8023532_1", target="_blank">W3.2</a>
<td><b>Mand: 8, 10, 16, 19, 27, 34. </b><br>Rec: 2, 3, 18, 20, 26, 32, 36, 40.
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 3 </strong></FONT></th></tr>

<tr style="background-color: aqua;">
<td>&sect;3.3</td>
<td>6/14 Mo</td>
<td>Cramer's Rule and Volumes</td>
<td><a href="https://www.youtube.com/watch?v=sRLwoK4cdNY&list=PLCyMqkq53VeSk8M3Y6ybj8UvZwld__6a6&index=4" target="_blank">D4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/d4cramers.pdf" target="_blank">D4pdf</a>, <a href="https://www.youtube.com/watch?v=3ndVGb1jFws&list=PLCyMqkq53VeSk8M3Y6ybj8UvZwld__6a6&index=5" target="_blank">D5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/D5volume.pdf" target="_blank">D5pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA33/XA33", target="_blank">XA3.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653870_1", target="_blank">W3.3</a>
<td><b>Mand: 6, 22, 23, 26. </b><br>Rec: 4, 5, 29, 30.
</tr>
<tr style="background-color: thistle;">
<td>&sect;4.1</td>
<td>6/15 Tu</td>
<td>Vector Spaces & Subspaces</td>
<td><a href="https://www.youtube.com/watch?v=QWslTQLnx7Q&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=1" target="_blank">B1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B1vecSpaces.pdf" target="_blank">B1pdf</a>, <a href="https://www.youtube.com/watch?v=M7MqpKdRPpQ&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=2" target="_blank">B2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B2vecSubspaces.pdf" target="_blank">B2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA41/XA41", target="_blank">XA4.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653889_1", target="_blank">W4.1</a>
<td><b>Mand: 3, 8, 13, 23, 31. </b><br>Rec: 1, 12, 15, 17, 22, 32.
</tr>


<tr style="background-color: thistle;">
<td>&sect;4.2</td>
<td>6/15 Tu</td>
<td>Null Spaces, Columns Spaces and Linear Transf.</td>
<td><a href="https://www.youtube.com/watch?v=19h4_43QLvU&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=3" target="_blank">B3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B3nullspace.pdf" target="_blank">B3pdf</a>, <a href="https://www.youtube.com/watch?v=lPAyQbiN9o8&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=4" target="_blank">B4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B4colSpace.pdf" target="_blank">B4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA42/XA42", target="_blank">XA4.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653858_1", target="_blank">W4.2</a>
<td><b>Mand: 11, 17, 25, 33, 34. </b><br>Rec: 3, 6, 14, 19, 21, 24, 32, 36.
</tr>

<tr style="background-color: aqua;">
<td>&sect;4.3</td>
<td>6/16 We</td>
<td>Bases and Linearly Independent Sets</td>
<td><a href="https://www.youtube.com/watch?v=Eu6p0y_XZfw&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=5" target="_blank">B5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B5bases.pdf" target="_blank">B5pdf</a>, <a href="https://www.youtube.com/watch?v=CBo9b1eYDts&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=6" target="_blank">B6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B6basesNulCol.pdf" target="_blank">B6pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA43/XA43", target="_blank">XA4.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653864_1", target="_blank">W4.3</a>
<td><b>Mand: 14, 21, 23, 29, 30. </b><br>Rec: 3, 4, 8, 10, 15, 24, 31.
</tr>

<tr style="background-color: thistle;">
<td>&sect;4.4</td>
<td>6/17 Th</td>
<td>Coordinate Systems</td>
<td><a href="https://www.youtube.com/watch?v=3EJu1YBlb0w&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=7" target="_blank">B7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B7coordinates.pdf" target="_blank">B7pdf</a>, <a href="https://www.youtube.com/watch?v=x4HZhHPyVkQ&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=8" target="_blank">B8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B8coordIsom.pdf" target="_blank">B8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA44/XA44", target="_blank">XA4.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653878_1", target="_blank">W4.4</a>
<td><b>Mand: 13, 15, 17, 21, 32. </b><br>Rec: 2, 3, 5, 7, 10, 11, 23.
</tr>

<tr style="background-color: aqua;">
<td>&sect;4.5</td>
<td>6/19 Sa</td>
<td>Dimension of a Vector Space</td>
<td><a href="https://www.youtube.com/watch?v=ox0gP-GGgwo&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=9", target="_blank">B9</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584453_1", target="_blank">B9pdf</a>, <a href="https://www.youtube.com/watch?v=dS_VWdgRDko&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=11", target="_blank">B10</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584452_1", target="_blank">B10pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA45/XA45", target="_blank">XA4.5</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8165230_1", target="_blank">W4.5</a>
<td><b>Mand: 8, 21, 23, 26, 29. </b><br>Rec: 1, 4, 11, 14, 28.
</tr>

<tr style="background-color: aqua;">
<td>&sect;4.6</td>
<td>6/19 Sa</td>
<td>Rank</td>
<td><a href="https://www.youtube.com/watch?v=ZwUVZzQpUdA&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=11" target="_blank">B11</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B11rank.pdf" target="_blank">B11pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA46/XA46", target="_blank">XA4.6</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8165231_1", target="_blank">W4.6</a> 
<td><b>Mand: 7, 17, 24, 27, 28. </b><br>Rec: 2, 5, 10, 13, 19.
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 4 </strong></FONT></th></tr>

<tr style="background-color: thistle;">
<td>&sect;4.7</td>
<td>6/21 Mo</td>
<td>Change of Basis</td>
<td><a href="https://www.youtube.com/watch?v=5F_MxsmEfdA&list=PLCyMqkq53VeRqffrKcrCVGXd5yxY1I7si&index=12" target="_blank">B12</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/B12ChangeBasis.pdf" target="_blank">B12pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA47/XA47", target="_blank">XA4.7</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653861_1", target="_blank">W4.7</a>
<td><b>Mand: 3, 11, 13, 15. </b><br>Rec: 1, 5, 7, 9.
</tr>
<tr style="background-color: aqua;">
<td>&sect;5.1</td>
<td>6/22 Tu</td>
<td>Eigenvectors & Eigenvalues</td>
<td><a href="https://www.youtube.com/watch?v=Q3eFAtHltVg&list=PLCyMqkq53VeQASKy7SDbZcv7TdIPkirS3&index=1" target="_blank">F1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F1eigen.pdf" target="_blank">F1pdf</a>, <a href="https://www.youtube.com/watch?v=LiRpubaX3ho&list=PLCyMqkq53VeQASKy7SDbZcv7TdIPkirS3&index=2" target="_blank">F2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F2GeomEigen.pdf" target="_blank">F2pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA51/XA51", target="_blank">XA5.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210079_1", target="_blank">W5.1</a>
<td><b>Mand: 2, 6, 13, 21, 23, 31. </b><br />Rec: 7, 11, 15, 19, 24, 25, 27. 
</tr>
<tr style="background-color: aqua;">
<td>&sect;5.2</td>
<td>6/22 Tu</td>
<td>Characteristic Equation</td>
<td><a href="https://www.youtube.com/watch?v=ha0TCLagbDg&list=PLCyMqkq53VeQASKy7SDbZcv7TdIPkirS3&index=3" target="_blank">F3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F3charEqn.pdf" target="_blank">F3pdf</a>, <a href="https://www.youtube.com/watch?v=VThOcK0aSBY&list=PLCyMqkq53VeQASKy7SDbZcv7TdIPkirS3&index=4" target="_blank">F4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F4Similarity.pdf" target="_blank">F4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA52/XA52", target="_blank">XA5.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210081_1", target="_blank">W5.2</a>
<td><b>Mand: 9, 19, 21. </b><br>Rec: 2, 5, 12, 15, 20.
</tr>


<tr style="background-color: thistle;">
<td>&sect;5.3</td>
<td>6/23 We</td>
<td>Diagonalization</td>
<td><a href="https://www.youtube.com/watch?v=iE8K8_nW0QA&list=PLCyMqkq53VeQASKy7SDbZcv7TdIPkirS3&index=5" target="_blank">F5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F5diagonalization.pdf" target="_blank">F5pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA53/XA53", target="_blank">XA5.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653877_1", target="_blank">W5.3</a>
<td><b>Mand: 11, 21, 24, 26. </b><br>Rec: 1, 4, 5, 9, 15, 17.
</tr>
<tr style="background-color: aqua;">
<td>§1.1–5.3</td>
<td>6/24 Th</td>
<td>Catchup &amp; Review Day</td>
<td> </td>
<td> </td>
<td> </td>
<td><b>Do Practice Midterm by today!</b></td>
</tr>


<tr><th style="background-color: lightgreen;" colspan=7 align="center"><font size=4>
<strong> FRIDAY 25 JUNE:  SECOND MIDTERM EXAM (through &sect;5.3)<br>
   <font color="red"> Tentatively 8:00PM&ndash;10:00PM</font></strong></FONT></th></tr>


<tr style="background-color: thistle;">
<td>&sect;5.4</td>
<td>6/27 Su</td>
<td>Eigenvectors & Linear Transformations</td>
<td><a href="https://www.youtube.com/watch?v=BrbNB-C8Dkg&list=PLCyMqkq53VeQASKy7SDbZcv7TdIPkirS3&index=6" target="_blank">F6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F6factoringLinTrans.pdf" target="_blank">F6pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA54/XA54", target="_blank">XA5.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653865_1", target="_blank">W5.4</a> 
<td><b>Mand: 6, 7, 10, 15, 25. </b><br>Rec: 1, 3, 16, 23.
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 5 </strong></FONT></th></tr>


<tr style="background-color: aqua;">
<td>&sect;6.1</td>
<td>6/28 Mo</td>
<td>Inner Product & Orthogonality</td>
<td><a href="https://www.youtube.com/watch?v=858cSuHqF-Q&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=1" target="_blank">G1</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G1innerProd.pdf" target="_blank">G1pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA61/XA61", target="_blank">XA6.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210082_1", target="_blank">W6.1</a>
<td><b>Mand: 3, 5, 19, 25, 27, 29. </b><br>Rec: 10, 16, 18, 23.
</tr>

<tr style="background-color: thistle;">
<td>&sect;6.2</td>
<td>6/29 Tu</td>
<td>Orthogonal Sets</td>
<td><a href="https://www.youtube.com/watch?v=-LCwaKaId98&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=2" target="_blank">G2</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G2orthoSetsSpaces.pdf" target="_blank">G2pdf</a>, <a href="https://www.youtube.com/watch?v=75Ap97hzA8s&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=3" target="_blank">G3</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G3orthonormality.pdf" target="_blank">G3pdf</a>, <a href="https://www.youtube.com/watch?v=Gkt8nZxrycQ&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=4" target="_blank">G4</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G4orthoProj.pdf" target="_blank">G4pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA62/XA62", target="_blank">XA6.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210086_1", target="_blank">W6.2</a>
<td><b>Mand: 8, 14, 23, 27, 28, 29. </b><br>Rec: 3, 6, 9, 11, 20, 21, 26.
</tr>

<tr style="background-color: thistle;">
<td>&sect;6.3</td>
<td>6/29 Tu</td>
<td>Orthogonal Projections</td>
<td><a href="https://www.youtube.com/watch?v=NFyCJGtqDpA&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=5" target="_blank">G5</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G5projApprox.pdf" target="_blank">G5pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA63/XA63", target="_blank">XA6.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653883_1", target="_blank">W6.3</a>
<td><b>Mand: 1, 7, 17, 21, 24. </b><br>Rec: 6, 9, 11, 13, 23.
</tr>

<tr style="background-color: aqua;">
<td>&sect;6.4</td>
<td>6/30 We</td>
<td>Gram-Schmidt</td>
<td><a href="https://www.youtube.com/watch?v=O3pz0nRPlrQ&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=6" target="_blank">G6</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G6gramSchmidt.pdf" target="_blank">G6pdf</a>, <a href="https://www.youtube.com/watch?v=w001lFfdeNs&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=7" target="_blank">F7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F7qr.pdf" target="_blank">F7pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA64/XA64", target="_blank">XA6.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210088_1", target="_blank">W6.4</a>
<td><b>Mand: 17, 19. </b><br>Rec: 1, 3, 7, 9, 11.
</tr>

<tr style="background-color: thistle;">
<td>&sect;6.5</td>
<td>7/1 Th</td>
<td>Least-Squares Problems</td>
<td><a href="https://www.youtube.com/watch?v=EqyUVWg-nVg&list=PLCyMqkq53VeS6MIHlurpODcSBk2-acbLv&index=7" target="_blank">G7</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/G7leastSquares.pdf" target="_blank">G7pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA65/XA65", target="_blank">XA6.5</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210090_1", target="_blank">W6.5</a>
<td><b>Mand: 3, 17, 19, 21. </b><br>Rec: 5, 7, 9, 11.
</tr>

<tr style="background-color: aqua;">
<td>§GPR</td>
<td>7/2 Fr</td>
<td>Google PageRank (Extra Credit)</td>
<td> </td>
<td> </td>
<td><!--  <td> --></td>
<td> </td>
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 6 </strong></FONT></th></tr>

<tr style="background-color: thistle;">
<td>&sect;7.1</td>
<td>7/5 Mo</td>
<td>Diagonalization of Symmetric Matrices</td>
<td><a href="https://www.youtube.com/watch?v=kkKyIPgN1Yc&list=PLCyMqkq53VeQVdULZlrM0gcectoBJMNYz&index=1" target="_blank">F8</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F8diagSymmMxs.pdf" target="_blank">F8pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA71/XA71", target="_blank">XA7.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210092_1", target="_blank">W7.1</a>
<td><b>Mand: 1, 3, 5, 8, 13, 25. </b><br>Rec: 10, 17, 19, 29.
</tr>

<tr style="background-color: aqua;">
<td>&sect;7.2</td>
<td>7/6 Tu</td>
<td>Quadratic Forms</td>
<td><a href="https://www.youtube.com/watch?v=JabOq1XZi9c&list=PLCyMqkq53VeQVdULZlrM0gcectoBJMNYz&index=2" target="_blank">F9</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F9quadForms.pdf" target="_blank">F9pdf</a>, <a href="https://www.youtube.com/watch?v=0rR3BwFId0w&list=PLCyMqkq53VeQVdULZlrM0gcectoBJMNYz&index=3" target="_blank">F10</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F10classifyingQF.pdf" target="_blank">F10pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA72/XA72", target="_blank">XA7.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210094_1", target="_blank">W7.2</a>
<td><b>Mand: 8, 11, 21, 27. </b><br>Rec: 1, 5, 13, 19.
</tr>

<tr style="background-color: aqua;">
<td>&sect;7.3</td>
<td>7/6 Tu</td>
<td>Constrained Optimization</td>
<td><a href="https://www.youtube.com/watch?v=nGT_FtYuZEU&list=PLCyMqkq53VeQVdULZlrM0gcectoBJMNYz&index=4" target="_blank">F11</a>,
<a href="http://www.math.uconn.edu/~troby/VLpdfs/F11ConstrOptQF.pdf" target="_blank">F11pdf</a>,</td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA73/XA73", target="_blank">XA7.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8911881_1", target="_blank">W7.3</a>
<td><b>Mand: 1, 3, 7, 11. </b><br>Rec: 5.
</tr>

<tr style="background-color: thistle;">
<td>&sect;7.4</td>
<td>7/7 We</td>
<td>Singular Value Decomposition</td>
<td><a href="https://www.youtube.com/watch?v=PMYaXYsGyfw&list=PLCyMqkq53VeQVdULZlrM0gcectoBJMNYz&index=5" target="_blank">F12</a>,<a href="http://www.math.uconn.edu/~troby/VLpdfs/F12svdA.pdf" target="_blank">F12pdf</a>,
<!--  <td></td> --></td>
<td>No XA7.4</a></td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/735f49e0e38d4392b76cb9b669b277001d", target="_blank">F12</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-8213248_1", target="_blank">F12pdf</a></td>
<td><b>Mand: 3, 9, 17, 19. </b><br />Rec: 1, 11, 18. 
</tr>

<tr style="background-color: aqua;">
<td>§1.1–7.4</td>
<td>7/8 Th</td>
<td>Catchup &amp; Review Day</td>
<td> </td>
<td> </td>
<td> </td>
<td><b>Do Practice Final by today!</b></td>
</tr>


<tr><th style="background-color: lightgreen;" colspan=7 align="center"><font size=4>
<strong> FRIDAY 9 JULY: FINAL EXAM (through &sect;7.4)<br>
   <font color="red"> Tentatively 8:00PM&ndash;11:00PM</font></strong></FONT></th></tr>

</tbody>
</table>
</center>

<HR>

<h3>Additional Web Resources </h3>

<UL>
<LI> <a href="http://buzzard.ups.edu/">Rob Beezer</a> has
  a <a href="http://linear.ups.edu/">free open-source textbook</a> in
  linear algebra that uses the open-source software
  package <a href="http://sagemath.org">Sage</a> for computations.  You can
  download a print edition, or view
  the <a href="http://linear.ups.edu/html/fcla.html">online hyperlinked 
  version</a>.  (This text is geared a bit more for those transitioning to theoretical math
  courses.)  
  <br><br>

<li> A <a href="http://joshua.smcvt.edu/linearalgebra/" target="_blank">free textbook by Jim Hefferon</a>
  <br><br>

 <li> Another <a href="https://www.math.ucdavis.edu/~anne/linear_algebra/" target="_blank">free textbook with a more abstract focus by Anne Schilling and her students</a>
  <br><br>
<li> Our text's <a href="https://www.pearson.com/us/higher-education/product/Lay-Linear-Algebra-and-Its-Applications-4th-Edition/9780321385178.html?tab=resources"
    target="_blank">useful site with review sheets and downloadable data</a>
  <br><br>

<li> <a href="http://web.mit.edu/18.06/www/"> The MIT 18.06 (Linear
Algebra) website </a> has lots of resources, including Mathlets (small
web-based teaching tools) (called "Demos" under
  the <a href="http://web.mit.edu/18.06/www/extras.shtml">Extras link</a>.).  
See also <a href="http://math.mit.edu/linearalgebra">resources related to
    Strang's standard textbook <i>Introduction to Linear Algebra</i></a>, in its 5th
  edition as of 2016. (This text is more geared towards applications.) 
<a href="http://math.mit.edu/~gs/">Strang's</a> video lectures are available on YouTube, or cataloged at
the <a href="https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/"> 
MIT 18.06 Course Website for Fall 2011</a>. 
  <br><br>

<li> The <i>3Blue1Brown</i> <a href="https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab" target="_blank">Essence
    of Linear Algebra video animations</a> 
<br><br>

<LI> <a href="http://math.mercyhurst.edu/~lwilliams/Applets/algebra/linearTransformations.php">A
    Linear Transformation Viewer</a>
    by <a href="http://math.mercyhurst.edu/~lwilliams">Lauren K. Williams</a>.
<br><br>





<li> This is a brief <a href="http://www2.imm.dtu.dk/~pch/Projekter/Google.pdf">blurb on how Google
    ranks pages</a> when you give is a search query and 
a <a href="http://www.ams.org/samplings/feature-column/fcarc-pagerank"> 
more detailed accessible exposition</a>  from
the <a href="http://www.ams.org/samplings/samplings">AMS math samplings website</a>. 
  <br><br>

<!--  <li> <a -->
<!--  href="http://www.math.ucla.edu/~tao/resource/general/115a.3.02f/Gauss.html"> -->
<!--  A Gaussian Elimination (row reduction) applet from Terry Tao's website </a>   <br><br> -->

<!--  <li> <a href="http://maven.smith.edu/~patela/Applets/transf_index.html"> -->
<!--  A linear transformation applet for the plane from Smith College </a> -->
<!--    <br><br> -->

<!--  <li> Here's another <a href="http://www.cohomology.com/rref/"> Online -->
<!--  Row Reducer</a> from Greg Landwebber's <a -->
<!--  href="http://www.cohomology.com/">Cohomology.com</a> website.  -->
<!--    <br><br> -->

<li> An <a href="http://www.ams.org/samplings/feature-column/fcarc-svd"> elementary exposition of
  the singular value decomposition</a> from
the <a href="http://www.ams.org/samplings/samplings">AMS math samplings website</a>. 
  <br><br>

<LI> Here's
  an <a href="http://www.flashlightcreative.net/swf/mindreader/">Online
  Mind Reader</a>.  Can you figure out how it works?</LI> 
<!--Created by Andy Naughton; search for "online mind reader add digits,
  subtract" -->

</UL>



<p></p>

