<title>Math 5020 Spring 2017 (Roby)</title>

<span class="mathtitle">Tom Roby's Math 5020 Home Page (Fall 2020)</span><br>
<span class="mathtitle">Enumerative Combinatorics
</span> 

<!-- <img class="mypic" ALIGN=right WIDTH=140 HEIGHT=145 HSPACE=50
     src="~troby/images/6888crop.jpg"> -->
<img class="mypic" ALIGN=right WIDTH=130 HEIGHT=200 HSPACE=50 src="~troby/images/bestock09lant.jpg"> 


<h3>Questions or Comments?</h3>
<ul>

  <li><A HREF="mailto:tom.roby@uconn.eduTR">Send me email (click here and
delete my initials at end)</A>.  

  <li> Homepage: <a href="http://www.math.uconn.edu/~troby">
http://www.math.uconn.edu/~troby</a>
  <li>Office:  MONT 239; Phone:  860-486-8385 <br>
  <li>Office hours:  Tues/Thurs 3:20&ndash;3:45, right after class, 
  and by appointment in MONT 239.  You can often find me in my office on TuTh mornings.  I'm
  happy to answer questions or schedule appointments by email, which I check frequently. 
</ul> 

<HR>


<h2>Class Information</h2>


<p class="mathpar"><i> COORDINATES:  </i>  Classes meet Tuesdays and Thursdays
2:00-3:15 in MONT 245.  
The registrar calls this Section 001. 

<p class="mathpar"><i> PREREQUISITES:  </i> MATH 5120 (Graduate Abstract Algebra) or consent
of instructor.  </p> 

<p class="mathpar"> <i> TEXT:</i> <a
href="http://www-math.mit.edu/~rstan/">Richard P. Stanley</a>: <a
href="http://www-math.mit.edu/~rstan/ec/">
<i>Enumerative Combinatorics 1 (2nd edition) & 2</i></a>. A near-final version of EC1Ed2
(useful for searching) and
many other resources can be downloaded therefrom. It's a good idea to start <a
href="http://www-math.mit.edu/~rstan/photos/fans/thomas.jpg">reading the text as early as possible</a>.
</p>    

<p class="mathpar"> <i>OTHER REFERENCES:</i> 

The following texts and treatises are at the graduate or advanced undergraduate level.  They
may provide useful alternative points of view or more leisurely presentations of some of the
material we will cover.  (I'm not including here the much longer list of books concerned
with more specialized topics related to representation theory, polytopes, etc.) 

<ul> 
<li> M. Aigner: <i>Combinatorial Theory (Classics in Mathematics)</i>, Springer, 1979
  (reprint 2013).  
<li> M. Aigner: <i>A Course in Enumeration (GTM)</i>, Springer, 2007.  
<li> M. Bona:   <i>Combinatorics of Permutations</i>, Chapman and Hall/CRC, 2004. 
<li> M. Bona:   <i>Introduction to Enumerative Combinatorics</i>, McGraw-Hill, 2005.
<li> M. Bona:   <i>A Walk Through Combinatorics: An Introduction to Enumeration and Graph
  Theory</i>, World Scientific, 2002, 2006, 2011. 
<li> L. Comtet: <i>Advanced Combinatorics</i>, Reidel/Kluwer, 1974. 
<li> I. Goulden & D. Jackson: <i>Combinatorial Enumeration</i>, Wiley, 1983; Dover reprint,
  2004. 
<li> J. van Lint & R. Wilson: <i>A Course in Combinatorics</i>, Cambridge, 2001.  
<li> R. Merris: <i>Combinatorics</i>, Wiley, 2003. 
<li> R. Stanley: <a href="http://www-math.mit.edu/~rstan/algcomb/index.html"><i>Algebraic
  Combinatorics: Walks, Trees, Tableaux, and More</i></a>, Springer UTM, 2013.
  
<li> H. Wilf: <i>Generatingfunctionology</i>,
  Academic Press 1990, 1994: A. K. Peters, 2006.  (2nd edition is 
<a"href="http://www.math.upenn.edu/~wilf/DownldGF.html">freely downloadable</a>). 
</p>
</ul>


<p class="mathpar"><i> WEB RESOURCES: </i> The homepage for this course is <a
href="http://www.math.uconn.edu/~troby/math5020s17">
http://www.math.uconn.edu/~troby/math5020s17</a>. 


<p><i>SOFTWARE:</i> While doing some computations by hand is generally essential for
   learning, having software that can do bigger computations or check one's work is very
   useful.  The free open-source computer algebra system
   <a href="http://www.sagemath.org">Sage</a> has an extensively-developed collection of
   objects and algorithms for algebraic combinatorics with various documentation
   including <a href="http://www.sagemath.org/doc/thematic_tutorials/">thematic
   tutorials</a>.  More generally, <a href="http://www.mat.univie.ac.at/~kratt/">Christian Krattenthaler</a> has kindly compiled a
   comprehensive list of <a href="http://www.mat.univie.ac.at/~slc/divers/software.html">Combinatorial software and
   databases</a>.  
</p>

<p><i> GRADING:</i>  Your grade will be based on several HW assignments, and possibly a
  short oral exam given near the end of the term.  Assignments will consists of
  problems at a variety of difficulty levels, of which you are to hand in at most
  3&ndash;4.  You should only write up carefully and hand in your best work, i.e., the
  hardest problems you were able to solve well.  It's fine to do the easier problems if
  you're new to combinatorics or too busy with more important things (like giving job
  talks).  This won't count against your grade.</p>  

<p> The text is loaded with exercises, most of them with solutions, though the latter often
are brief outlines, sometimes with pointers to the research literature.  Stanley's knowledge
of the subject is encylopedic, and he was able include a large amount of interesting material
this way.  If I assign an exercise whose solution is already included, I'll expect much more
detail in what you hand in.  I recommend you browse through many of the unassigned exercises
to get a sense for what's there.</p>

<p class="mathpar"> You may find some homework problems to be
challenging, leading you to spend lots of time working on them and
sometimes get frustrated.  This is natural.  I encourage you to work
with others, or to ask me for hints.  It's OK to get
significant help from any resource, but in the end, please write your
own solution in your own words.  Do not simply copy another student's work or obtain a
solution from an outside source.  <b>Copying someone else's work
without credit is plagiarism and will be dealt with according
to <a href="http://community.uconn.edu/the-student-code-appendix-a/">university
policy</a>.</b> More importantly, it is a poor learning strategy.

<p><i> <a href="http://www.math.uconn.edu/~troby/math5020s17/problemsEC.php">HOMEWORK
PROBLEMS:</a></i> Problem assignments and details on how problems are weighted is available
<a href="http://www.math.uconn.edu/~troby/math5020s17/problemsEC.php">here</a>.  


<p class="mathpar"><i> ACADEMIC INTEGRITY:</i>  Please make sure you
  are familiar with and abide by
<a href="http://policy.uconn.edu/2014/04/11/policy-on-scholarly-integrity-in-graduate-education-and-research/">
 Policy on Scholarly Integrity in Graduate and Post-Doctoral Education and Research</a>.  
<!--  FOR UNDERGRADS
<a  href="http://community.uconn.edu/the-student-code-appendix-a/">The
  Student Code governing Academic Integrity in Undergraduate Education
  and Research.</a>  -->
</p>

<p class="mathpar"><i> ACKNOWLEDGEMENTS: </i>  Many people have
  influenced my approach to this material, particularly Richard Stanley, but also Ira
  Gessel, Jim Propp, and Gian-Carlo Rota. This term my initial plan is to follow the
  lectures Stanley gave at MIT in Fall 2016 when he taught a version of this course, but
  with whatever modifications make sense.</p>


<p class="mathpar"><i> CONTENT: </i> Enumerative Combinatorics is a beautiful and
deep subject which has lately forged strong connections with many other parts of
mathematics.  This course will focus on the basic techniques of enumeration, with a strong
emphasis on generating functions and bijective proofs.  In particular, the initial plan is
to cover much of Chapters 1,2,4,5, and 6 of EC1 and EC2, leaving out the large chapters on
partially-ordered sets and symmetric functions, each of which could be a course on its own.  

<p class="mathpar"> <i>ACCESSIBILITY &  DISABILITY ISSUES: </i> Please
  contact me and UConn's <a href="http://www.csd.uconn.edu/">Center for
  Students with Disabilities</a> as soon as possible if you have any
  accessibility issues, have a (documented) disability and wish to
  discuss academic accommodations, or if you would need assistance in
  the event of an emergency. </p>

<p class="mathpar"><i> LEARNING: </i> <b> The only way to learn
mathematics is by doing it! </b> Complete each assignment to the best of
your ability, and get help when you are confused.  Come to class
prepared with questions.  Don't hesitate to seek help from other
students.  Sometimes the point of view of someone who has just figured
something out can be the most helpful. </p>

<p class="mathpar">
<center>

<TABLE BORDER=0 CELLPADDING=3 BGCOLOR="#DDDDDD">
<TR><th align=center bgcolor="#FFFFFF" colspan=4><font size=4>
<strong>5020 LECTURE SCHEDULE </strong></FONT></th></tr>
<tr><th align=center  colspan=4> </th></tr>
<TR><td> <tdalign=center><FONT SIZE=3><strong>Date </strong></td>
<td><FONT SIZE=3><strong>Section </strong></td>
<td> <tdalign=center><FONT SIZE=3><strong>Topics </strong></td>


<TR style="background-color:aqua;">
<td> 1/17 T
<td> &sect;1.1
<td> How to count, generating functions

<TR style="background-color:aqua;">
<td> 1/19 R
<td> &sect;1.2
<td> Generating functions, binomial coefficients


<TR style="background-color:thistle;">
<td> 1/24 T
<td> &sect;1.2
<td> Compositions, multisets, multinomial coefficients

<TR style="background-color:thistle;">
<td> 1/26 R
<td> &sect;1.3
<td> Permutations: cycles, cycle indicators, Renyi-Foata map 

<TR style="background-color:aqua;">
<td> 1/31 T
<td> 
<td> SNOW DAY (Class cancelled)

<TR style="background-color:aqua;">
<td> 2/2 R
<td> &sect;1.3
<td> Stirling numbers (1st kind), <i>q</i>-counting inversions

<TR style="background-color:thistle;">
<td> 2/7 T
<td> &sect;1.7
<td> <i>q</i>-counting inversions for multiset permutations, <i>q</i>-multinomial
coefficients, integer partitions 

<TR style="background-color:thistle;">
<td> 2/9 R
<td> 
<td> SNOW DAY (Class cancelled)

<TR style="background-color:aqua;">
<td> 2/14 T
<td> &sect;1.4, 1.7
<td> <i>q</i>-binomial coeff. count partitions in rectangle, permutation descents

<TR style="background-color:aqua;">
<td> 2/16 R
<td> 
<td> SICK DAY (Class cancelled)

<TR style="background-color:thistle;">
<td> 2/21 T
<td> &sect; 1.4
<td> Eulerian polynomials & Eulerian numbers, summing <i>d</i>th powers. 

<TR style="background-color:thistle;">
<td> 2/23 R
<td> &sect;1.4&ndash;5
<td> Alternating permutations, Tree representations of permutations

<TR style="background-color:aqua;">
<td> 2/28 T
<td> &sect;1.8
<td> Integer partition identities

<TR style="background-color:aqua;">
<td> 3/2 R
<td> &sect;1.8
<td> Euler's pentagonal number theorem

<TR style="background-color:thistle;">
<td> 3/7 T
<td> &sect;1.8+
<td> Jacobi's triple product formula, Jacobi's identity, Ramanujuan's <i>p(5k+4)</i>
congruence. 

<TR style="background-color:thistle;">
<td> 3/9 R
<td> &sect;1.9
<td> Sti2ling numbers (2nd kind) 

<tr><th align=center bgcolor="#AAAAAA" colspan=3><font size=4>
<strong>  11&ndash;19 MARCH SPRING BREAK (NO CLASS MEETINGS) </strong></FONT></th></tr>

<TR style="background-color:aqua;">
<td> 3/21 T
<td> &sect;2.1
<td> Sieve methods Principle of Inclusion-Exclusion (PIE)

<TR style="background-color:aqua;">
<td> 3/23 R
<td> &sect;2.2
<td> Generalized PIE, derangements, Sti2ling Numbers. 

<TR style="background-color:thistle;">
<td> 3/28 
<td> &sect;2.2
<td> Counting and <i>q</i>-counting permutations by descent set

<TR style="background-color:thistle;">
<td> 3/30 R
<td> &sect;5.1
<td> Products and compositions of generating functions (20min before Number Theory Day)

<TR style="background-color:aqua;">
<td> 4/4 T
<td> &sect;5.1
<td> The Compositional and exponential formulae

<TR style="background-color:aqua;">
<td> 4/6 R
<td> &sect;5.1&ndash;2
<td> Examples of compositional and exponential formulae

<TR style="background-color:thistle;">
<td> 4/11 T
<td> &sect;5.1&ndash;2
<td> Permutation version of exponential formula, more examples

<TR style="background-color:thistle;">
<td> 4/13 R
<td> &sect;5.3
<td> Enumerating trees and symmetric matrices with all line sums 2

<TR style="background-color:aqua;">
<td>4/18 T
<td> &sect;5.4 
<td> Lagrange inversion, enumerating <i>k</i>-ary trees

<TR style="background-color:aqua;">
<td> 4/20 R
<td> &sect;5.5
<td> Enumeration of matrices with all line sums 2

<TR style="background-color:thistle;">
<td> 4/25 T
<td> &sect;5.6
<td> Directed graph version of Matrix-Tree theorem

<TR style="background-color:thistle;">
<td> 4/27 R
<td> &sect;5.6
<td> Matrix-Tree theorem and applications

<!--  <TR style="background-color:thistle;"><td> &sect;1.1-7.4 -->
<!--  <td> 5/1 R -->
<!--  <td> Catchup & Review Day -->
<!--  <td>  -->

<!--  <tr><th align=center bgcolor="#00FFFF" colspan=3><font size=4> -->
<!--  <strong> TBD  MAY 8:00PM&ndash;10:00PM  FINAL REVIEW IN MSB 215 </strong></FONT> (Do <a href="~troby/math2210f16/Handouts/pf.pdf">Practice Final</a> by today)</th></tr> 

<tr><th align=center bgcolor="#AAAAAA" colspan=3><font size=4>
<strong>  THURSDAY 15 DECEMBER 3:30&ndash;5:30  FINAL REVIEW IN/NEAR MONT 225 </strong></FONT></th></tr>


<tr><th align=center bgcolor="#AAAAAA" colspan=3><font size=4>
<strong>  SATURDAY 17 DECEMBER 10:30&ndash;12:30  FINAL EXAM IN MONT 225 </strong></FONT></th></tr>
<strong> <\!--  TUESDAY 6 MAY 10:30&ndash;12:30 -\-> TBD  FINAL EXAM IN MONT 225 </strong></FONT></th></tr> -->

</table>
</center>
</p>
<br>

<HR>

<h3> Web Resources </h3>
<UL>
<li> The <a href="http://www.combinatorics.org/">Electronic Journal of Combinatorics</a> has
high quality survey articles as well as cutting-edge research</a>;

<li> A longstanding series of conferences in Europe with concommitant journal, the <a
href="http://www.emis.de/journals/SLC/divers/aboutslc.html">Séminaire Lotharingien de
Combinatoire</a>;

<li> <a href="http://wiki.sagemath.org/combinat">Sage-Combinat</a> is the open source
extensible toolbox which has made Sage extremely useful for students and researchers in
algebraic combinatorics. A thematic tutorial linked to <a href="http://www-math.mit.edu/~rstan/algcomb/index.html">Stanley's undergraduate algebraic text</a> has been started <a href="http://doc.sagemath.org/html/en/thematic_tutorials/algebraic_combinatorics.html">here</a> by <a href="https://www.math.ucdavis.edu/~anne/">Anne Schilling</a>;  

<li> <a href="http://math.sfsu.edu/federico/">Federico Ardila</a> has bravely 
videotaped his graduate-level courses in a variety of topics in combinatorics (Enumeration,
Combinatorial commutative lagebra, Coxeter groups, Hopf algebras, Matroids, Polytopes) and
<a href="http://math.sfsu.edu/federico/teaching.html">made them available</a>.  
</UL>


<HR>

<HR>
<h2> NEWS, NOTES, AND HANDOUTS </h2>

<h3>Handouts</h3>

<!--
<p>
<UL>
<LI> <a href="~troby/math2210f16/Handouts/pfF16.pdf">Practice Final</a></LI>
<LI> <a href="~troby/math2210f16/Handouts/pfF16Solns.pdf">Solutions to Practice Final</a></LI>

</UL>
</p>
-->

<HR>
<p class="mathpar">Back to my <a href="~troby/index.php">home page</a>.<br> </>

</body>
</html>



