<title>Math 2210 Summer 2019 (Roby)</title>

<h3>
<span class="mathtitle"><a href="http://www2.math.uconn.edu/~troby/math2210sum19/index.php" target="_blank">Tom Roby's Math 2210Q Home Page (Summer 2019)</a></span><br>
<span class="mathtitle">Applied Linear Algebra</span>
 <h2><b><i><p style="color:#FF0000";>See PROCTORED EXAM and COURSE PACE notes (in Red) below!</p></i></b></h2>

</h3>

<img class="mypic" ALIGN=right WIDTH=130 HEIGHT=200 HSPACE=50 src="http://www2.math.uconn.edu/~troby/images/bestock09lant.jpg"> 


<h3>Questions or Comments?</h3>
<ul>

  <li><i>For questions about the <b>course material</b> or structure:</i> Please ask in the
  approriate discussion forum in Piazza/HuskyCT. 

  <li><i>For questions about using HuskyCT:</i> Once you are logged in to <a href="https://learn.uconn.edu/", target="_blank">HuskyCT</a>, click Student Help in the top bar.

  <li><i>For questions about your grade:</i> Please email the TA managing grades for the course: 
 <A HREF="mailto:yoshimi.dilg@uconn.edu">Yoshimi Dilg</a>.

   <li><i>For questions about enrollment or suggestions for improving future versions of the
   course:</i> Please email the Professor: <A HREF="mailto:tom.roby@uconn.eduTR">Tom
   Roby</A> (delete initials from end).  

  <li><i>Professor's Homepage:</i> <a href="http://www2.math.uconn.edu/~troby">
http://www2.math.uconn.edu/~troby</a>
  <li><i>Office hours</i>: Office hours will be held online.  Times and 
  online platform are announced on the HuskyCT course home page.  
  <!--  If there is sufficient interest, there may also be some on-campus office hours as well.  -->
  We are also happy to respond to questions and comments within the Piazza discussion forum, which we check
  regularly.   
</ul> 

<HR>


<h2>Class Information</h2>

<p><i>INSTRUCTIONAL TEAM:</i>  
<ul>
<li><i>Lead Instructor:</i> <a href="http://www2.math.uconn.edu/~troby">Tom Roby</a>; 
<li><i>Teaching Assistants:</i> <A HREF="mailto:gianmarco.molino@uconn.edu">Gianmarco Molino</a>;
<li><i>Teaching Assistants:</i> <A HREF="mailto:matthew.plante@uconn.edu">Matthew Plante</a>;
<li><i>Teaching Assistants:</i> <A HREF="mailto:yoshimi.dilg@uconn.edu">Yoshimi Dilg</a>. 
</ul>
<p><i> COORDINATES:</i>  Classes meet online, and you can find everything
you need linked within Husky CT.  

<p><i> PREREQUISITES:</i> MATH 1132 (Calculus II), 1152 (Honors Calculus
  II), OR 2142 (Advanced Calculus II).</p> 

<p> <i> TEXT:</i> You will need to obtain a copy of the textbook, which is <a
href="https://www-math.umd.edu/people/item/380-lay.html">David C. Lay's</a>
textbook 
<i>Linear Algebra and Its Applications</i></a>.  Any edition you can find from the 3rd on
should be fine for this class, except that the problem numbers may vary slightly. I recommend any version that
you can get cheaply.  The homework solutions are
written for the <a href="http://wps.aw.com/aw_lay_linearalgebra_4">4th Ed.</a>; a few of the numerical
problems have different numbers, and a few of the theoretical problems are have different problem numbers.  

<p><i> WEB RESOURCES:</i> The information for this course will be available
and updated in two places:  
  <b> (1)</b> On the HuskyCT site; and
  <b> (2)</b> On the current website
<a
href="http://www2.math.uconn.edu/~troby/math2210sum19">
http://www2.math.uconn.edu/~troby/math2210sum19</a>. </p>

<p> Other resources (in no particular order):
  <ul>
    <li> A <a href="http://joshua.smcvt.edu/linearalgebra/">free textbook by Jim Hefferon</a>;
    <li> Another <a href="https://www2.math.ucdavis.edu/~anne/linear_algebra/">free textbook with a more abstract focus by Anne Schilling and her students</a>;
    <li> The <i>3Blue1Brown</i> <a href="https://www2.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab">Essence
    of Linear Algebra video animations</a> ;
    <li> Our text's <a href="http://wps.aw.com/aw_lay_linearalgebra_4">useful site with review sheets and downloadable data</a>.  
  </ul>
</p>


<p><i>SOFTWARE:</i> In most areas of mathematics it is
  frequently helpful to use computer software not only for computations,
  but also to explore examples, search for patterns, or test
  conjectures.  For linear algebra there are several extensive
  and sophisticated commercial software packages, including MATLAB,
  Maple, and Mathematica.  Matlab is particularly good at linear
  algebra for applications.  All of these can be expensive, depending on
  your site license, but are 
<a href="http://software.uconn.edu">currently
  available to UConn students</a>.</p>

<p>An excellent alternative to the above is the free
  open-source computer algebra
  system <a href="http://www.sagemath.org">Sage</a>.  There are many
  commands for linear algebra, and a textbook (linked below) has been
  written that makes significant use of Sage examples.  Sage also
  provides a full-fledged programming environment via the
<a href="http://en.wikipedia.org/wiki/Python_%28programming_language%29">Python
  programming language</a>, but you don't need to be a programmer to use
  it.  I highly recommend trying it out online, and installing a copy
  on your computer.</p>

<p><i> GRADING:</i>  Your grade will be based on two midterm exams, a final
exam, worksheets, homework and participation. </p>

The breakdown of points is:<br> <br>

<center>
<TABLE BORDER="4" CELLPADDING="2">
<tr><th> Midterms <th> Final <th> Worksheets  <th> Homework <th> Participation </tr>
<tr><th>20% each <th>30% <th>12% <th> 8% <th>10% </tr>
</TABLE>
</center>
<p></p>

<p><i>EXAMS:</i> All exams will be <b>in-person</b> and <b>proctored on
campus</b>.  The dates are already scheduled (see below), so please mark your
calendars now.  All exams (like math itself at this level)
are cumulative. No makeups will be given; instead if you have an approved reason for missing
an exam, the final will count for the appropriately higher percentage. If you miss the final
for reasons <b>approved by the Dean of Students</b>, then you will have one chance to take a
make-up final exam in early September. </p>

<h2><b> 
<p style="color:#FF0000";>ALL STUDENTS WILL BE
REQUIRED TO TAKE AN IN-PERSON FINAL ON THE STORRS CAMPUS, EITHER ON THE LAST DAY OF THE
SESSION OR THE OFFICAL MAKEUP DAY (3rd week of the Fall term).  YOU MUST GET AT LEAST 60% ON
THE FINAL TO PASS THE CLASS.  NO EXCEPTIONS!</p></b></h2>

<p><i>STUDENT WORKFLOW:</i> In the course schedule, each section in the text has a single
line indicating the topic, which may correspond to multiple video lectures. For each section
you should:

<ol>
<li> WATCH the VIDEO LECTURE(S) & take notes (pdfs of slides are available);
<li> DO the XIMERA ACTIVTIES as a self check;
<li> DO the WORKSHEET problems and SUBMIT them by the deadline on the schedule;
<li> USE the PIAZZA DISCUSSION BOARD and ONLINE OFFICE HOURS <b>anytime</b> you get seriously stuck;
<li> CHECK your WORKSHEET against the solutions (posted the morning after the due date);
<li> READ the TEXTBOOK to fill in gaps, see an alternate presentation, straighten out
confusing points; 
<li> DO as many HW problems as you can, and SUBMIT them the day AFTER the worksheet is due;
<li> CHECK your HW against the solutions (posted the morning after the due date);
</ol>
</p>

<p style="color:#FF0000";>Note that many days have multiple sections due.  This course will be <b>fast-paced</b> and cover
the <i>full semester's worth of material</i>.  Please make sure you clear your calendar to
allow adequate time for all the activities and for the material to sink in.  If you have a
full-time job, plan to have no social life.   
I strongly encourage you to <b>work ahead
whenever possible</b>, since you never know when circumstances beyond your control may conspire
to set you behind.  Catch-up time is much more limited than during a regular term.  
</p>

<p><i>VIDEO LECTURES:</i> There are short video lectures, one or more for each
section.  I recommend (a) trying to watch them at higher speed (1.4x&ndash;2x) if they make sense, 
(b) rewinding to rewatch any parts you find confusing, and (c) watching them again later in
the course to review (e.g., before exams). 

<p> <i>XIMERA:</i> Ximera provides an interactive platform for
  self-testing your understanding of the material.  There is one Ximera activity for each
  section/topic. These will only count towards your participation grade since they are meant
  to be formative rather than summative.</p>

<p> <i>PIAZZA:</i> The Piazza discussion board is what makes this class a community since we do not meet in
person. We use Piazza because of its excellent ability to include math notation using LaTeX/MathJax.  The
quality and quantity of your posts in Piazza count towards your participation grade.  If you don't have
questions, please try to help out your fellow students who might be confused.</p>

<p> <i>PARTICIPATION:</i> Your participation grade will be a linear combination (with positive coefficients) 
of your completed Ximera activities, your participations in class surveys, and your posts on
Piazza (at least a couple each week).</p> 

<p> <i>WORKSHEETS:</i> Every section has a worksheet of basic problems.  Attempt these as soon as you're
ready, and upload your written solutions in HuskyCT (as a readable PDF file) by 11:59PM on the due date.
(Generally if a submission arrives no more than 2 hours late, we will count it as "on time".)  Solutions to
these will be released shortly afterwards.  These will be graded for completion rather than accuracy.
<br><br>

<i><b>IMPORTANT:</b> HuskyCT does not handle other image formats as well as PDF, so please make sure you
upload in PDF format.  There are free apps (e.g., "CamScanner") that allow you to take a picture with a smart
phone that is immediately converted to PDF.</i> </p>

<p> <i>HOMEWORK:</i> Homework is assigned for each section, and is due one day AFTER the corresponding
worksheet (again uploaded as a PDF by 11:59PM, with a 2-hour grace period).  The problems are grouped as
<i>Mandatory (Mand.)</i> and <i>Recommended (Rec.)</i>.  As with the worksheets, solutions to these will be
released shortly afterwards, and they will be graded for completion rather than accuracy.  In order to be
well-prepared for exams you should be able to do all the homework problems.</p>

<p> You may find some homework problems to be challenging, leading you to spend lots of time working on them
and sometimes get frustrated.  This is natural.  I encourage you to work with other people in person or
electronically.  It's OK to get significant help from any resource, but in the end, please write your own
solution in your own words.  <b>Copying someone else's work without credit is plagiarism and will be dealt
with according to <a href="http://community.uconn.edu/the-student-code-appendix-a/">university policy</a>.</b>
Equally importantly, it is a poor learning strategy.

<p><i> LATE/UNREADABLE ASSIGNMENTS:</i> Late homework and worksheets (up to 24 hours beyond the 2-hour grace
period) will receive half credit, after that none.  Homework and worksheets that are not easily readable
(e.g., because of bad photo quality) will not be graded and will not receive credit. An app such as CamScanner
on a smartphone can help produce very readable PDF images of your work. </p>

<p><i> ACADEMIC INTEGRITY:</i> Please make sure you are familiar with and abide by <a
  href="http://community.uconn.edu/the-student-code-appendix-a/">The Student Code governing Academic Integrity
  in Undergraduate Education and Research.</a> For exams you may not discuss the material with anyone other
  than the instructor or offical proctor, and no calculators, phones, slide rules or other devices designed to
  aid communication or computation may be used unless otherwise specifically indicated on the exam.  </p>

<p><i> CONTENT:</i> Linear Algebra is a beautiful and important subject, rich in applications within
mathematics and to many other disciplines. For many of you this is the first course to begin bridging the gap
between concrete computations and abstract reasoning.  Understanding the notions of vector spaces, linear
(in)dependence, dimension, and linear transformations will help you make sense of matrix manipulations at a
deeper level, clarifying the underlying structure.  </p>

<p> <i>ACCESSIBILITY & DISABILITY ISSUES:</i> Please contact me and UConn's <a
  href="http://www.csd.uconn.edu/">Center for Students with Disabilities</a> as soon as possible if you have
  any accessibility issues, have a (documented) disability and wish to discuss academic accommodations, or if
  you would need assistance in the event of an emergency. </p>

<p><i> LEARNING:</i> <b> The only way to learn
mathematics is by doing it! </b> Complete each assignment to the best of
your ability, and get help when you are confused.  Take advantage of the online discussions
and office hours and the wealth of information on the web.   </p>


<center>
<table border="0" cellpadding="3" bgcolor="#DDDDDD">
<tbody>
<tr style="background-color: grey;"><td colspan="100%"></td></tr>

<tr><th colspan="7" align="center"><span size="4" style="font-size: large;"><strong>2210Q LECTURE AND ASSIGNMENT SCHEDULE </strong></span></th></tr>
<tr style="background-color: grey;"><td colspan="100%"></td></tr>

<!--  <tr><th colspan="7" align="center"> </th></tr> -->
<tr>
<td><span size="3" style="font-size: medium;"><strong>Section </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Due Date </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Topics </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Videos </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Ximera </strong></span></td>
<td style="text-align: center;"><span size="3" style="font-size: medium;"><strong>Worksheet </strong></span></td>
<td><span size="3" style="font-size: medium;"><strong>Homework (due next day)</strong></span></td>
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 1 </strong></FONT></th></tr>


<tr style="background-color: aqua;">
<td>&sect;1.1</td>
<td>7/15 Mo</td>
<td>Intro to Linear Alg &amp; Systems of Eqns.</a></td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/d3693532549b4020ad9c740c7517959c1d", target="_blank">E1</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584092_1", target="_blank">E1pdf</a>, 
<a href="https://mediasite.dl.uconn.edu/Mediasite/Play/78ba9210242b4a61befbdf0a321020a21d", target="_blank">E2</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584091_1", target="_blank">E2pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA11/XA11", target="_blank">XA1.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7649910_1", target="_blank">W1.1</a>
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7653820_1", target="_blank">W1.1soln</a></td> -->
<td><b>Mand: 3, 12, 21, 24, 25, 31. </b><br>Rec: 1, 2, 10, 13, 15, 16, 32. 
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7647843_1", target="_blank">HW1.1soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;1.2</td>
<td>7/16 Tu</td>
<td>Row Reduction & Echelon Forms</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/d2ea78d8934f4ace82b4613632ea6bf21d", target="_blank">E3</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584090_1", target="_blank">E3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/14de2bc27d2f4f9f8fd93b65cdbc72bd1d", target="_blank">E4</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584089_1", target="_blank">E4pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA12/XA12", target="_blank">XA1.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7714627_1", target="_blank">W1.2</a>
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7781454_1", target="_blank">W1.2soln</a> -->
</td>
<td><b>Mand: 2, 13, 19, 21, 24. </b><br>Rec: 10, 14, 29, 31. 
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584097_1", target="_blank">HW1.2soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;1.3</td>
<td>7/16 Tu</td>
<td>Vector Equations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/1992e569eb2e478daf339620c6ee41231d", target="_blank">E5</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584088_1", target="_blank">E5pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA13/XA13", target="_blank">XA1.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7714628_1", target="_blank">W1.3</a>
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7781455_1", target="_blank">W1.3soln</a></td> -->
<td><b>Mand: 6, 7, 15, 21, 23, 25. </b><br>Rec: 3, 9, 12, 14, 22.
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584098_1", target="_blank">HW1.3soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;1.4</td>
<td>7/17 We</td>
<td>Matrix Equations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/bd862e8c40c743adbc54c6e6350f3d7c1d", target="_blank">E7</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584100_1", target="_blank">E7pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/556a7ebe7d0847d097ff438992b5d65e1d", target="_blank">E8</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584099_1", target="_blank">E8pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA14/XA14", target="_blank">XA1.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653879_1", target="_blank">W1.4</a>
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584401_1", target="_blank">W1.4soln</a></td> -->
<td><b>Mand: 1, 13, 17, 19, 22, 23, 25. </b><br>Rec: 4, 7, 9, 11, 31.
<!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584402_1", target="_blank">HW1.4soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;1.5</td>
<td>7/18 Th</td>
<td>Solution Sets of Linear Systems</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/c2722b4af646425d9dd7033c3e093b6c1d", target="_blank">E9</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584404_1", target="_blank">E9pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/5d031432fb1c498eadf7ccd53cc01fd51d", target="_blank">E10</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584403_1", target="_blank">E10pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA15/XA15", target="_blank">XA1.5</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653853_1", target="_blank">W1.5</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584406_1", target="_blank">W1.5soln</a></td> -->
<td><b>Mand: 11, 15, 19, 23, 30, 32.</b><br>Rec: 2, 6, 18, 22, 27.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584405_1", target="_blank">HW1.5soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;1.7</td>
<td>7/18 Th</td>
<td>Linear Independence</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/56dd0274692a44bdadf817683dba735f1d", target="_blank">E11</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584408_1", target="_blank">E11pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/468a60e79e004b528e2410922bf7981e1d", target="_blank">E12</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584407_1", target="_blank">E12pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA17/XA17", target="_blank">XA1.7</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7784384_1", target="_blank">W1.7</a> 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7841184_1", target="_blank">W1.7soln</a></td> -->
<td><b>Mand: 1, 7, 15, 16, 20, 21. </b><br>Rec: 2, 5, 9, 32, 34, 35.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584410_1", target="_blank">HW1.7soln</a></td> -->
</tr>
<tr style="background-color: aqua;">
<td>&sect;1.8</td>
<td>7/20 Sa</td>
<td>Linear Transformations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/cf40116b4d504922a572109add6fd1521d", target="_blank">M2</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584411_1", target="_blank">M2pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA18/XA18", target="_blank">XA1.8</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7799321_1", target="_blank">W1.8</a> 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7898658_1", target="_blank">W1.8soln</a></td> -->
<td><b>Mand: 2, 8, 9, 21, 31.</b><br>Rec: 4, 13, 15, 17.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584412_1", target="_blank">HW1.8soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;1.9</td>
<td>7/20 Sa</td>
<td>Matrix of Linear Transformations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/3b02a4ff18ec4eb7ba37c28cc57dc1401d", target="_blank">M3</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584413_1", target="_blank">M3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/af4d1a9822f54594a642c9f6f76dbc7e1d", target="_blank">M4</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7891305_1", target="_blank">M4pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA19/XA19", target="_blank">XA1.9</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653855_1", target="_blank">W1.9</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584414_1", target="_blank">W1.9soln</a></td> -->
<td><b>Mand: 1, 8, 13, 19, 23, 26, 34. </b><br>Rec: 2, 7, 9, 15, 20, 32, 36.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584415_1", target="_blank">HW1.9soln</a></td> -->
</tr>


<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 2 </strong></FONT></th></tr>


<tr style="background-color: thistle;">
<td>&sect;2.1</td>
<td>7/22 Mo</td>
<td>Matrix Operations and Inverses</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/81c731662fd243a4bc6c31f7607b35ba1d", target="_blank">M5</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584417_1", target="_blank">M5pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/f501b8c89eee4b009ad4a55e7b380ced1d", target="_blank">M6</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584416_1", target="_blank">M6pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA21/XA21", target="_blank">XA2.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653874_1", target="_blank">W2.1</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584418_1", target="_blank">W2.1soln</a></td> -->
<td><b>Mand: 5, 7, 10, 15. </b><br>Rec: 2, 18, 20, 22, 27, 28.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584419_1", target="_blank">HW2.1soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;2.2</td>
<td>7/22 Mo</td>
<td>Inverse of a Matrix</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/980d135dd77342f693ac9c92d3d9970b1d", target="_blank">M7</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584421_1", target="_blank">M7pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/22060b043bf84f7cab85cc2c448c28fc1d", target="_blank">M8</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584420_1", target="_blank">M8pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA22/XA22", target="_blank">XA2.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7834059_1", target="_blank">W2.2</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7933909_1", target="_blank">W2.2soln</a></td> -->
<td><b>Mand: 9, 11, 15, 16, 29. </b><br>Rec: 3, 6, 7, 13, 23, 24, 32, 37.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584423_1", target="_blank">HW2.2soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;2.3</td>
<td>7/23 Tu</td>
<td>Characterizations of Invertible Matrices</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/ec56df10c9db4b8f94180f1a13434bfa1d", target="_blank">M9</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584424_1", target="_blank">M9pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA23/XA23", target="_blank">XA2.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7834060_1", target="_blank">W2.3</a> 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7933910_1", target="_blank">W2.3soln</a></td> -->
<td><b>Mand: 11, 13, 15, 28. </b><br>Rec: 1, 3, 5, 8, 17, 26, 35.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584425_1", target="_blank">HW2.3soln</a></td> -->
</tr>

<tr><th style="background-color: lightgreen;" colspan=7 align="center"><font size=4>
<strong> WEDNESDAY 24 JULY: FIRST MIDTERM EXAM (through &sect;2.3)<br>
   <font color="red"> 1:30&ndash;3:00 pm, Monteith 104,  UConn Storrs campus</font></strong></FONT></th></tr>

<tr style="background-color: thistle;">
<td>&sect;3.1</td>
<td>7/25 Th</td>
<td>Intro to Determinants</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/44f79da4c91c4709bc26f5022935e8b71d", target="_blank">D1</a>,
   <a href="https://lms.uconn.edu/bbcswebdav/xid-7584426_1", target="_blank">D1pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA31/XA31", target="_blank">XA3.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8023531_1", target="_blank">W3.1</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8023561_1", target="_blank">W3.1soln</a></td> -->
<td><b>Mand: 13, 20, 21, 37, 39. </b><br>Rec: 4, 8, 11, 31, 32.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584428_1", target="_blank">HW3.1soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;3.2</td>
<td>7/25 Th</td>
<td>Properties of Determinants</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/9be3c7b281114205825846b7436d2f4d1d",
target="_blank">D2</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584430_1", target="_blank">D2pdf</a>,
<a href="https://mediasite.dl.uconn.edu/Mediasite/Play/51ced837d31447828e4ab71f7fb132bc1d",
target="_blank">D3</a>, 
   <a href="https://lms.uconn.edu/bbcswebdav/xid-7584429_1", target="_blank">D3pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA32/XA32", target="_blank">XA3.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8023532_1", target="_blank">W3.2</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8023560_1", target="_blank">W3.2soln</a></td> -->
<td><b>Mand: 8, 10, 16, 19, 27, 34. </b><br>Rec: 2, 3, 18, 20, 26, 32, 36, 40.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584431_1", target="_blank">HW3.2soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;3.3</td>
<td>7/27 Sa</td>
<td>Cramer's Rule and Volumes</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/420e2c5c5e1e4bf09421da8a53f531e21d", target="_blank">D4</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584433_1", target="_blank">D4pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/d75c06b28c9e4431b636e28ae0dbb1d51d", target="_blank">D5</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584432_1", target="_blank">D5pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA33/XA33", target="_blank">XA3.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653870_1", target="_blank">W3.3</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584434_1", target="_blank">W3.3soln</a></td> -->
<td><b>Mand: 6, 22, 23, 26. </b><br>Rec: 4, 5, 29, 30.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584435_1", target="_blank">HW3.3soln</a></td> -->
</tr>
<tr style="background-color: aqua;">
<td>&sect;4.1</td>
<td>7/27 Sa</td>
<td>Vector Spaces & Subspaces</td>
<td><a href="
https://mediasite.dl.uconn.edu/Mediasite/Play/f3427889ef3d484c8a866dd6497de2591d", target="_blank">B1</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584437_1", target="_blank">B1pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/9cfebcc6653c4df0b596da13c1ffbbad1d", target="_blank">B2</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584436_1", target="_blank">B2pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA41/XA41", target="_blank">XA4.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653889_1", target="_blank">W4.1</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584438_1", target="_blank">W4.1soln</a></td> -->
<td><b>Mand: 3, 8, 13, 23, 31. </b><br>Rec: 1, 12, 15, 17, 22, 32.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584439_1", target="_blank">HW4.1soln</a></td> -->
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 3 </strong></FONT></th></tr>

<tr style="background-color: thistle;">
<td>&sect;4.2</td>
<td>7/29 Mo</td>
<td>Null Spaces, Columns Spaces and Linear Transf.</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/adb301fd9a8848bcaea2290626b834b61d", target="_blank">B3</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584441_1", target="_blank">B3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/5a8b0ea4646348c9b33b045b65a282841d", target="_blank">B4</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584440_1", target="_blank">B4pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA42/XA42", target="_blank">XA4.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653858_1", target="_blank">W4.2</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584442_1", target="_blank">W4.2soln</a></td> -->
<td><b>Mand: 11, 17, 25, 33, 34. </b><br>Rec: 3, 6, 14, 19, 21, 24, 32, 36.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584443_1", target="_blank">HW4.2soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;4.3</td>
<td>7/29 Mo</td>
<td>Bases and Linearly Independent Sets</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/8a63a8f199f94700b40b693c0934448b1d", target="_blank">B5</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584445_1", target="_blank">B5pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/31449adac7fa48dcbe67fdeed90f2b8e1d", target="_blank">B6</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584444_1", target="_blank">B6pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA43/XA43", target="_blank">XA4.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653864_1", target="_blank">W4.3</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584446_1", target="_blank">W4.3soln</a></td> -->
<td><b>Mand: 14, 21, 23, 29, 30. </b><br>Rec: 3, 4, 8, 10, 15, 24, 31.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584447_1", target="_blank">HW4.3soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;4.4</td>
<td>7/30 Tu</td>
<td>Coordinate Systems</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/8740cc29d5594b6bbe12c24dcea204291d", target="_blank">B7</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584449_1", target="_blank">B7pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/da8173b6b2a24b25b20f91c4df99ca2d1d", target="_blank">B8</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584448_1", target="_blank">B8pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA44/XA44", target="_blank">XA4.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653878_1", target="_blank">W4.4</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584450_1", target="_blank">W4.4soln</a></td> -->
<td><b>Mand: 13, 15, 17, 21, 32. </b><br>Rec: 2, 3, 5, 7, 10, 11, 23.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584451_1", target="_blank">HW4.4soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;4.5</td>
<td>7/31 We</td>
<td>Dimension of a Vector Space</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/e4c4b50655b649f399d0c229521c82d81d", target="_blank">B9</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584453_1", target="_blank">B9pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/cfc6c046105b4c3aba4db15fa60b1b221d", target="_blank">B10</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584452_1", target="_blank">B10pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA45/XA45", target="_blank">XA4.5</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8165230_1", target="_blank">W4.5</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8165233_1", target="_blank">W4.5soln</a></td> -->
<td><b>Mand: 8, 21, 23, 26, 29. </b><br>Rec: 1, 4, 11, 14, 28.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584455_1", target="_blank">HW4.5soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;4.6</td>
<td>7/31 We</td>
<td>Rank</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/74e48adf1c594cccb439fec32d23cd361d", target="_blank">B11</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584456_1", target="_blank">B11pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA46/XA46", target="_blank">XA4.6</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8165231_1", target="_blank">W4.6</a> 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8165232_1", target="_blank">W4.6soln</a></td> -->
<td><b>Mand: 7, 17, 24, 27, 28. </b><br>Rec: 2, 5, 10, 13, 19.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584457_1", target="_blank">HW4.6soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;4.7</td>
<td>8/1 Th</td>
<td>Change of Basis</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/268c13d18d5b453bb80f88aecf3ac0e41d", target="_blank">B12</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584458_1", target="_blank">B12pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA47/XA47", target="_blank">XA4.7</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653861_1", target="_blank">W4.7</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584459_1", target="_blank">W4.7soln</a></td> -->
<td><b>Mand: 3, 11, 13, 15. </b><br>Rec: 1, 5, 7, 9.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584460_1", target="_blank">HW4.7soln</a></td> -->
</tr>
<tr style="background-color: thistle;">
<td>&sect;5.1</td>
<td>8/3 Sa</td>
<td>Eigenvectors & Eigenvalues</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/524fe7b9d37e42c9ad77c6f3c8924bc61d
", target="_blank">F1</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584462_1", target="_blank">F1pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/97bdf293786640888623a6e8cde923391d", target="_blank">F2</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584461_1", target="_blank">F2pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA51/XA51", target="_blank">XA5.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210079_1", target="_blank">W5.1</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210078_1", target="_blank">W5.1soln</a></td> -->
<td><b>Mand: 2, 6, 13, 21, 23, 31. </b><br />Rec: 7, 11, 15, 19, 24, 25, 27. 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584463_1", target="_blank">HW5.1soln</a></td> -->
</tr>
<tr style="background-color: thistle;">
<td>&sect;5.2</td>
<td>8/3 Sa</td>
<td>Characteristic Equation</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/f0e46c4ada36466980dbe274d307ae8e1d", target="_blank">F3</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584465_1", target="_blank">F3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/0d786fbc404d4e129c8eac47926e3d9a1d", target="_blank">F4</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584468_1", target="_blank">F4pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA52/XA52", target="_blank">XA5.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210081_1", target="_blank">W5.2</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210080_1", target="_blank">W5.2soln</a></td> -->
<td><b>Mand: 9, 19, 21. </b><br>Rec: 2, 5, 12, 15, 20.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584466_1", target="_blank">HW5.2soln</a></td> -->
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 4 </strong></FONT></th></tr>

<tr style="background-color: aqua;">
<td>&sect;5.3</td>
<td>8/5 Mo</td>
<td>Diagonalization</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/434a2a8e772c49b6973de2f7c893520d1d", target="_blank">F5</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584467_1", target="_blank">F5pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA53/XA53", target="_blank">XA5.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653877_1", target="_blank">W5.3</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584469_1", target="_blank">W5.3soln</a></td> -->
<td><b>Mand: 11, 21, 24, 26. </b><br>Rec: 1, 4, 5, 9, 15, 17.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584470_1", target="_blank">HW5.3soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;5.4</td>
<td>8/6 Tu</td>
<td>Eigenvectors & Linear Transformations</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/2f64b8a985d741c58e09ca7a77aa81f21d", target="_blank">F6</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584471_1", target="_blank">F6pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA54/XA54", target="_blank">XA5.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653865_1", target="_blank">W5.4</a> 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584472_1", target="_blank">W5.4soln</a></td> -->
<td><b>Mand: 6, 7, 10, 15, 25. </b><br>Rec: 1, 3, 16, 23.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584473_1", target="_blank">HW5.4soln</a></td> -->
</tr>

<tr><th style="background-color: lightgreen;" colspan=7 align="center"><font size=4>
<strong> WEDNESDAY 7 AUGUST: SECOND MIDTERM EXAM (through &sect;5.3)<br>
   <font color="red"> 1:30&ndash;3:00 pm, Monteith 104,  UConn Storrs campus</font></strong></FONT></th></tr>

<tr style="background-color: aqua;">
<td>&sect;6.1</td>
<td>8/8 Th</td>
<td>Inner Product & Orthogonality</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/c28965cfa5e6472a9b59f9db90dccd0e1d", target="_blank">G1</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584474_1", target="_blank">G1pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA61/XA61", target="_blank">XA6.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210082_1", target="_blank">W6.1</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8684312_1", target="_blank">W6.1soln</a></td> -->
<td><b>Mand: 3, 5, 19, 25, 27, 29. </b><br>Rec: 10, 16, 18, 23.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584476_1", target="_blank">HW6.1soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;6.2</td>
<td>8/8 Th</td>
<td>Orthogonal Sets</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/4b418facfe384c7f98e0429436148a4e1d", target="_blank">G2</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584478_1", target="_blank">G2pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/b42e21fcd03a4f8696c7457ed68996681d", target="_blank">G3</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584477_1", target="_blank">G3pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/10b8d7400df74f05ab4840e84bf996e21d", target="_blank">G4</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584481_1", target="_blank">G4pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA62/XA62", target="_blank">XA6.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210086_1", target="_blank">W6.2</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210083_1", target="_blank">W6.2soln</a></td> -->
<td><b>Mand: 8, 14, 23, 27, 28, 29. </b><br>Rec: 3, 6, 9, 11, 20, 21, 26.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584479_1", target="_blank">HW6.2soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;6.3</td>
<td>8/10 Sa</td>
<td>Orthogonal Projections</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/0fdbae8667df44c891f4e44b0e5377001d", target="_blank">G5</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584480_1", target="_blank">G5pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA63/XA63", target="_blank">XA6.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-7653883_1", target="_blank">W6.3</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584482_1", target="_blank">W6.3soln</a></td> -->
<td><b>Mand: 1, 7, 17, 21, 24. </b><br>Rec: 6, 9, 11, 13, 23.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584483_1", target="_blank">HW6.3soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;6.4</td>
<td>8/10 Sa</td>
<td>Gram-Schmidt</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/a6fd13d067ea43b7a9e012e900918f431d", target="_blank">G6</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584485_1", target="_blank">G6pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/57e729953dc04f2baea1e0067f6e8bd01d", target="_blank">F7</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584484_1", target="_blank">F7pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA64/XA64", target="_blank">XA6.4</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210088_1", target="_blank">W6.4</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210087_1", target="_blank">W6.4soln</a></td> -->
<td><b>Mand: 17, 19. </b><br>Rec: 1, 3, 7, 9, 11.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584487_1", target="_blank">HW6.4soln</a></td> -->
</tr>

<tr><th style="background-color: grey;" colspan=7 align="center"><font size=4>
<strong> WEEK 5 </strong></FONT></th></tr>



<tr style="background-color: aqua;">
<td>&sect;6.5</td>
<td>8/12 Mo</td>
<td>Least-Squares Problems</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/1ba687131e184d459b04b0accf204a631d", target="_blank">G7</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-7584488_1", target="_blank">G7pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA65/XA65", target="_blank">XA6.5</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210090_1", target="_blank">W6.5</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210089_1", target="_blank">W6.5soln</a></td> -->
<td><b>Mand: 3, 17, 19, 21. </b><br>Rec: 5, 7, 9, 11.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584489_1", target="_blank">HW6.5soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;7.1</td>
<td>8/12 Mo</td>
<td>Diagonalization of Symmetric Matrices</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/c9db8ea6a3064bc1a82e905d7311b7ae1d", target="_blank">F8</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-8212175_1", target="_blank">F8pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA71/XA71", target="_blank">XA7.1</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210092_1", target="_blank">W7.1</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210091_1", target="_blank">W7.1soln</a></td> -->
<td><b>Mand: 1, 3, 5, 8, 13, 25. </b><br>Rec: 10, 17, 19, 29.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-7584491_1", target="_blank">HW7.1soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;7.2</td>
<td>8/13 Tu</td>
<td>Quadratic Forms</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/774da9289c904bb68a1c61b8ee9a6acf1d", target="_blank">F9</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-8213245_1", target="_blank">F9pdf</a>, <a href="https://mediasite.dl.uconn.edu/Mediasite/Play/7aab6ee2faee4bde8e4a252f908722dc1d", target="_blank">F10</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-8213246_1", target="_blank">F10pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA72/XA72", target="_blank">XA7.2</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8210094_1", target="_blank">W7.2</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8210093_1", target="_blank">W7.2soln</a></td> -->
<td><b>Mand: 8, 11, 21, 27. </b><br>Rec: 1, 5, 13, 19.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8986725_1", target="_blank">HW7.2soln</a></td> -->
</tr>

<tr style="background-color: thistle;">
<td>&sect;7.3</td>
<td>8/13 Tu</td>
<td>Constrained Optimization</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/e0a3b45c9b0447aeafcfaa34b344545b1d", target="_blank">F11</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-8213247_1", target="_blank">F11pdf</a></td>
<td><a href="https://ximera.osu.edu/course/UConnLinAlg/Activities/XA73/XA73", target="_blank">XA7.3</a></td>
<td><a href="https://lms.uconn.edu/bbcswebdav/xid-8911881_1", target="_blank">W7.3</a>
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-8986724_1", target="_blank">W7.3soln</a></td> -->
<td><b>Mand: 1, 3, 7, 11. </b><br>Rec: 5.
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-9021331_1", target="_blank">HW7.3soln</a></td> -->
</tr>

<tr style="background-color: aqua;">
<td>&sect;7.4</td>
<td>8/14 We</td>
<td>Singular Value Decomposition</td>
<td><a href="https://mediasite.dl.uconn.edu/Mediasite/Play/735f49e0e38d4392b76cb9b669b277001d", target="_blank">F12</a>, <a href="https://lms.uconn.edu/bbcswebdav/xid-8213248_1", target="_blank">F12pdf</a></td>
<td></td>
<td></td>
<td><b>Mand: 3, 9, 17, 19. </b><br />Rec: 1, 11, 18. 
   <!--  <a href="https://lms.uconn.edu/bbcswebdav/xid-9021330_1", target="_blank">HW7.4soln</a></td> -->
</tr>

<tr><th style="background-color: lightgreen;" colspan=7 align="center"><font size=4>
<strong> FRIDAY 16 AUGUST: FINAL EXAM (through &sect;7.4)<br>
   <font color="red"> 1:15&ndash;3:15 pm, Monteith 104,  UConn Storrs campus</font></strong></FONT></th></tr>

</tbody>
</table>
</center>

<p></p>



