<title>Math 2210 Fall 2016 (Roby)</title>

<span class="mathtitle">Tom Roby's Math 2210Q Home Page (Fall 2016)</span><br>
<span class="mathtitle">Applied Linear Algebra
</span> 

<!-- <img class="mypic" ALIGN=right WIDTH=140 HEIGHT=145 HSPACE=50
     src="~troby/images/6888crop.jpg"> -->
<img class="mypic" ALIGN=right WIDTH=130 HEIGHT=200 HSPACE=50 src="~troby/images/bestock09lant.jpg"> 


<h3>Questions or Comments?</h3>
<ul>

  <li><A HREF="mailto:tom.roby@uconn.eduTR">Send me email (click here and
delete my initials at end)</A>.  

  <li> Homepage: <a href="http://www.math.uconn.edu/~troby">
http://www.math.uconn.edu/~troby</a>
  <li>Office:  MONT 239; Phone:  860-486-8385 <br>
  <li>Office hours:  Tues/Thurs 1:30&ndash;1:55, right after class, 
  and by appointment in MONT 239.  I'm happy to answer
  questions or schedule appointments by email, which I check frequently.  
</ul> 

<HR>


<h2>Class Information</h2>


<p class="mathpar"><i> COORDINATES:  </i>  Classes meet Tuesdays and Thursdays
2:00-3:15 in MONT 225.  
<!--  <a href="http://classrooms.uconn.edu/msb215.htm">MSB 215</a>  -->
The registrar calls this Section 002, #2698.</p>  

<p class="mathpar"><i> PREREQUISITES:  </i> MATH 1132, 1152, OR 2142.</p> 

<p class="mathpar"> <i> TEXT:</i> <a href="https://www-math.umd.edu/people/item/380-lay.html">David C. Lay</a>: <a
href="http://wps.aw.com/aw_lay_linearalgebra_4">
<i>Linear Algebra and Its Applications, 4th Ed.</i></a>, available in
  the bookstore. Let me know if you have any trouble getting it.  

<p class="mathpar"><i> WEB RESOURCES: </i> The homepage for this course is <a
href="http://www.math.uconn.edu/~troby/math2210f16">
http://www.math.uconn.edu/~troby/math2210f16</a>. The author also has
  a useful site with review sheets and downloadable data
   <a href="http://wps.aw.com/aw_lay_linearalgebra_4">here</a>.  

<p class="mathpar"><i>SOFTWARE:</i> In most areas of mathematics it is
  frequently helpful to use computer software not only for computations,
  but also to explore examples, search for patterns, or test
  conjectures.  For linear algebra there are several extensive
  and sophisticated commercial software packages, including MATLAB,
  Maple, and Mathematica.  Matlab is particularly good at linear
  algebra for applications.  All of these can be expensive, depending on
  your site license.</p>

<p class="mathpar">An excellent alternative to the above is the free
  open-source computer algebra
  system <a href="http://www.sagemath.org">Sage</a>.  There are many
  commands for linear algebra, and a textbook (linked below) has been
  written that makes significant use of Sage examples.  Sage also
  provides a full-fledged programming environment via the
<a href="http://en.wikipedia.org/wiki/Python_%28programming_language%29">Python
  programming language</a>, but you don't need to be a programmer to use
  it.  I highly recommend trying it out online, and installing a copy
  on your computer.</p>

<p class="mathpar"><i> GRADING:</i>  Your grade will be based on two midterm exams, a final
exam, homework, and quizzes. </p>

<p class="mathpar"> The breakdown of points is: <br> <br>

<center>
<TABLE BORDER="4" CELLPADDING="2">
<tr><th> Midterms <th> Final <th> Quizzes  <th> Homework
<br> 
<tr><th>20% each <th>30% <th>20% <th>10% <br> 
</TABLE>
</center>
</p>

<p class="mathpar"><i> EXAMS: </i> The exam dates are already scheduled, so please mark your
calendars now (midterms in class on 29 September and 1 November at the usual time; final TBD
by registrar during the week of 12-16 December).  All exams (like math itself at this level)
are cumulative. No makeups will be given; instead if you have an approved reason for missing
an exam, the final will count for the appropriately higher percentage. </p>

<p class="mathpar"> <i> QUIZZES: </i> Quizzes will be given each Thursday (except
  midterm exam days), covering (a) sections from the previous week (at
  the level of HW exercises) and (b) the reading assigned for the
  current week (at the level of True/False exercises).  Your lowest two
  quiz scores will be dropped. Here is a sample <a href="~troby/math2210f16/Handouts/pq1.pdf">Practice Quiz</a> so you know
  ahead of time what the format will be.  (Solutions will be provided below.)</p>

<p class="mathpar"> <i> HOMEWORK:</i> Homework will be assigned most
  weeks, and is DUE at class the following TUESDAY.  Since I may discuss
  the homework problems in class the day they are due, late assignments
  will be accepted only under the most extreme circumstances. Please
  let me know as soon as possible if you find yourself with a situation that
  might qualify.  The lowest written homework score will be dropped in
  any event. I've color coded the schedule by week to help clarify what the HW
  is for a given week.

<p class="mathpar"> You may find some homework problems to be
challenging, leading you to spend lots of time working on them and
sometimes get frustrated.  This is natural.  I encourage you to work
with other people in person or electronically.  It's OK to get
significant help from any resource, but in the end, please write your
own solution in your own words.  <b>Copying someone else's work
without credit is plagiarism and will be dealt with according
to <a href="http://community.uconn.edu/the-student-code-appendix-a/">university
policy</a>.</b> More importantly, it is a poor learning strategy.


<p class="mathpar"><i> ACADEMIC INTEGRITY: </i>  Please make sure you
  are familiar with and abide by
<a  href="http://community.uconn.edu/the-student-code-appendix-a/">The
  Student Code governing Academic Integrity in Undergraduate Education
  and Research.</a>  For quizzes and exams you may not discuss the
  material with anyone other than the instructor or offical proctor, and
  no calculators, phones, slide rules or other devices designed to aid
  communication or computation may be used unless otherwise specifically
  indicated on the exam.    
</p>

<p class="mathpar"><i> CONTENT: </i> Linear Algebra is a beautiful and
important subject, rich in applications within mathematics and to many
other disciplines. For many of you this is the first course to begin bridging
  the gap between concrete computations and abstract reasoning.
  Understanding the notions of vector spaces, linear (in)dependence,
  dimension, and linear transformations will help you make sense of
  matrix manipulations at a deeper level, clarifying the underlying
  structure.  

<p class="mathpar"> <i>ACCESSIBILITY &  DISABILITY ISSUES: </i> Please
  contact me and UConn's <a href="http://www.csd.uconn.edu/">Center for
  Students with Disabilities</a> as soon as possible if you have any
  accessibility issues, have a (documented) disability and wish to
  discuss academic accommodations, or if you would need assistance in
  the event of an emergency. </p>

<p class="mathpar"><i> LEARNING: </i> <b> The only way to learn
mathematics is by doing it! </b> Complete each assignment to the best of
your ability, and get help when you are confused.  Come to class
prepared with questions.  Don't hesitate to seek help from other
students.  Sometimes the point of view of someone who has just figured
something out can be the most helpful. </p>

<p class="mathpar"> We will often spend classtime doing things in
groups, presenting mathematics to one another, or having interactive
discussions.  There will not be time to "cover" all material in a
lecture format so you will need to read and learn some topics on your
own from the book (or otherwise).   </p>

<!--
<p class="mathpar"> <i><a href="~troby/math2210f16/honors.html">HONORS
  CONVERSIONS</a>:</i> If you are in the Honors 
  Program, click on the link for information about converting this
  course to an honors version.  </p>
-->
<p class="mathpar"> <i>SCHEDULE:</i> I will update the following schedule
over the course of the semester.  Generally we will cover three sections
  per week, which means splitting a section between two
  lectures.  <b>Lecture notes are linked section by section:</b> I 
  recommend you review them before or after lecture, allowing you to
  spend lecture time focussing on the material rather than copying
  things down.  If you have a religious observance that conflicts with
  your participation in the course, please meet with me within the first
  two weeks of the term to discuss any appropriate accommodations.</p>

<center>
<p class="mathpar" style="background-color:thistle"> I've color coded
  the schedule by week to help clarify what the HW is for a given week.</p>
</center>

<p class="mathpar">
<center>
<TABLE BORDER=0 CELLPADDING=3 BGCOLOR="#DDDDDD">
<TR><th align=center bgcolor="#FFFFFF" colspan=4><font size=4>
<strong>2210Q LECTURE AND ASSIGNMENT SCHEDULE </strong></FONT></th></tr>
<tr><th align=center  colspan=4> </th></tr>
<TR><td><FONT SIZE=3><strong>Section </strong></td>
<td> <tdalign=center><FONT SIZE=3><strong>Date </strong></td>
<td> <tdalign=center><FONT SIZE=3><strong>Topics </strong></td>
<td><font size=3><strong>HW Problems</strong></font></td> 


<TR style="background-color:aqua;"><td> &sect;1.1
<td> 8/30 T
<td> <a href="~troby/math2210f16/LT/sec1_1.pdf">Intro to Linear Alg & Systems of Eqns.</a> 
<td> 1, 2, 3, 10, 12, 13, 15, 16, 21, 24, 25, 31, 32 

<TR style="background-color:aqua;"><td> &sect;1.2
<td> 9/1 R
<td> <a href="~troby/math2210f16/LT/sec1_2.pdf">Row Reduction & Echelon Forms</a>
<td> 2, 10, 13, 14, 19, 21, 24, 29, 31

<TR style="background-color:aqua;"><td> &sect;1.3
<td> 9/1 R
<td> <a href="~troby/math2210f16/LT/sec1_3.pdf">Vector Equations</a>
<td> 3, 6, 7, 9, 12, 14, 15, 21, 22, 23, 25 
     <!--  <font color="red"> due 1/30 </font>  -->

<TR style="background-color:thistle;"><td> &sect;1.4
<td> 9/6 T
<td> <a href="~troby/math2210f16/LT/sec1_4.pdf">Matrix Equations</a>
<td> 1, 4, 7, 9, 11, 13, 17, 19, 22, 23, 25, 31


<TR style="background-color:thistle;"><td> &sect;1.5
<td> 9/8 R
<td> <a href="~troby/math2210f16/LT/sec1_5.pdf">Solution Sets of Linear Systems</a>
<td> 2, 6, 11, 15, 18, 19, 22, 23, 27, 30 
  <!--  <font color="red">HW 1.3 due</font> -->

<TR style="background-color:aqua;"><td> &sect;1.7 
<td> 9/13 T
<td> <a href="~troby/math2210f16/LT/sec1_7.pdf">Linear Independence</a>
<td>   <p>1, 2, 5, 7, 9, 15, 16, 20, 21, 32, 35</p>

<TR style="background-color:aqua;"><td> &sect;1.8
<td> 9/13 T
<td> <a href="~troby/math2210f16/LT/sec1_8.pdf">Linear Transformations</a>
<td>   <p>2, 4, 8, 9, 13, 15, 17, 21, 26, 31</p>

<TR style="background-color:aqua;"><td> &sect;1.9
<td> 9/15 R
<td> <a href="~troby/math2210f16/LT/sec1_9.pdf">Matrix of Linear Transformation
<td>     <p>1, 2, 5, 13, 15, 20, 23, 26, 32, 34</p>

<TR style="background-color:thistle;"><td> &sect;2.1
<td> 9/20 T
<td> <a href="~troby/math2210f16/LT/sec2_1.pdf">Matrix Operations and Inverses</a>
<td>   <p>2, 5, 7, 10, 15, 20, 22, 27, 28</p>

<TR style="background-color:thistle;"><td> &sect;2.2
<td> 9/22 R
<td> <a href="~troby/math2210f16/LT/sec2_2.pdf">Inverse of a Matrix</a>
<td>     <p>3, 6, 7, 9, 11, 13, 15, 23, 24, 29, 32, 37</p>

<TR style="background-color:thistle;"><td> &sect;2.3
<td> 9/22 R
<td> <a href="~troby/math2210f16/LT/sec2_3.pdf">Characterizations of Invertible Matrices
<td>   <p>1, 3, 5, 8, 11, 13, 15, 17, 26, 28, 35, 40(challenge!)</p>

<!--  <TR style="background-color:aqua;">o<td> &sect;2.4  -->
<!--  <td> 2/18 T -->
<!--  <td> Partitioned matrices -->
<!--  <td>   <p>1, 4, 9, 10, 11, 13, 16, 19</p> -->

<TR style="background-color:aqua;"><td> Ch. 1
<td> 9/27 T
<td> Supplementary Exercises
<td>   <p>6, 7, 10 ,18, 22, 23</p>

<!--  <TR style="background-color:aqua;"><td> &sect;2.5 -->
<!--  <td> 2/20 R -->
<!--  <td> Matrix Factorizations -->
<!--  <td>   <p>2, 5, 7, 21, 23b, 24</p> -->

<TR style="background-color:aqua;"><td> &sect;3.1
<td> 9/27 T
<td> <a href="~troby/math2210f16/LT/sec3_1_and_2.pdf"> Intro to Determinants</a>
<td>   <p>4, 8, 11, 13, 20, 21, 31, 32, 37, 39</p>

<TR style="background-color:aqua;"><td> &sect;3.2
<td> 9/27 T
<td> <a href="~troby/math2210f16/LT/sec3_2.html">Properties of Determinants</a>
<td>   <p>2, 3, 8, 10, 16, 17, 20, 26, 27, 32, 34, 40</p>

<TR style="background-color:aqua;"><td> &sect;3.3
<td> 9/29 R
<td> <a href="~troby/math2210f16/LT/dne.html">Cramer's Rule & Volumes</a>
<td>   <p>4, 5, 6, 22, 23, 26, 29, 30;  

<TR style="background-color:thistle;"><td> &sect;1.1&ndash;2.5
<td> 10/4 T
<td> Catchup & Review Day
<td> <b>Do <a href="~troby/math2210f16/Handouts/pm1F16.pdf">Practice Midterm</a> by today!</b>

<tr><th bgcolor="#D8BFD8" colspan=4><font size=4>
<strong> THURSDAY 6 OCTOBER: FIRST MIDTERM EXAM (through &sect;2.3)<br> 
   <font color="red">HW  3.1&ndash;3.3 and Chapter 1 Suppl. due on 10/13</font></p> </strong></FONT></th></tr>

<TR style="background-color:aqua;"><td> &sect;4.1
<td> 10/11T
<td> <a href="~troby/math2210f16/LT/sec4_1.pdf">Vector Space & Subspaces</a>
<td>   <p>1, 3, 8, 12, 13, 15, 17, 22, 23, 31, 32</p>

<TR style="background-color:aqua;"><td> &sect;4.2
<td> 10/13 R
<td> <a href="~troby/math2210f16/LT/sec4_2.pdf">Null Spaces, Column Spaces & Lin. Transf.</a>
<td>   <p>3, 6, 11, 14, 17, 19, 21, 24, 25, 32, 33, 34, 36</p>

<TR style="background-color:thistle;"><td> &sect;4.3
<td> 10/18 T
<td> <a href="~troby/math2210f16/LT/sec4_3.pdf">Bases and Lin Ind. Sets</a>
<td>   <p>3, 4, 8, 10, 14, 15, 21, 23, 24, 29, 30, 31; 
</p>

<TR style="background-color:thistle;"><td> &sect;4.4
<td> 10/20 R
<td> <a href="~troby/math2210f16/LT/sec4_4.pdf">Coordinate Systems</a>
<td>   <p>2, 3, 5, 7, 10, 11, 13, 15, 17, 21, 23, 32 
   <!--  <font color="red">Midterm #1 rewrites due.</font></p> -->

<!--  <tr><th align=center bgcolor="#AAAAAA" colspan=4><font size=4> -->
<!--  <strong> 17-21 MARCH SPRING BREAK NO CLASSES  </strong></FONT></th></tr> -->

<TR style="background-color:aqua;"><td> &sect;4.5
<td> 10/25 T
<td> <a href="~troby/math2210f16/LT/sec4_5.pdf">Dimension of a VS</a>
<td>   <p>1, 4, 8, 11, 14, 21, 23, 26, 28, 29 </p>

<TR style="background-color:aqua;"><td> &sect;4.6
<td> 10/25 T
<td> <a href="~troby/math2210f16/LT/sec4_6.pdf">Rank</a>
<td>   <p>2, 5, 7, 10, 13, 19, 24, 27, 28; 
<!-- <font color="red">Midterm #1 Rewrite due</font></p> -->

<TR style="background-color:aqua;"><td> &sect;4.7
<td> 10/27 R
<td> <a href="~troby/math2210f16/Handouts/sec4_7-handwritten.pdf">Change of Basis</a>
<td>   <p>1, 3, 5, 7, 9, 11, 13, 15</p>

<TR style="background-color:thistle;"><td> &sect;5.1
<td> 11/1 T
<td> <a href="~troby/math2210f16/LT/sec5_1.pdf">Eigenvectors & Eigenvalues</a>
<td>   <p>2, 6, 7, 11, 13, 15, 19, 21, 23, 24, 25, 27, 31</p>

<TR style="background-color:thistle;"><td> &sect;5.2
<td> 11/1 T
<td> <a href="~troby/math2210f16/LT/sec5_2.pdf">Characteristic Equation</a>
<td>     <p>2, 5, 9, 12, 15, 19, 20, 21</p>

<TR style="background-color:thistle;"><td> &sect;5.3
<td> 11/3 R
<td> <a href="~troby/math2210f16/LT/sec5_3.pdf">Diagonalization</a>
<td>   <p>1, 4, 5, 9, 11, 15, 17, 21, 24, 26</p>

<TR style="background-color:aqua;"><td> &sect;5.4
<td> 11/8 T
<td> <a href="~troby/math2210f16/Handouts/sec5-4Notes.pdf">Eigenvectors & Linear Transformations</a>
<td>   <p>1, 3, 6, 7, 10 ,15, 16, 23, 25</p>


<TR style="background-color:aqua;"><td> &sect;6.1
<td> 11/8 T
<td> <a href="~troby/math2210f16/LT/sec6_1.pdf">Inner Product & Orthogonality</a>
<td>   <p>3, 5, 10, 16, 18, 19, 23, 25, 27, 29</p>

<TR style="background-color:aqua;"><td> &sect;6.2
<td> 11/10 R
<td> <a href="~troby/math2210f16/LT/sec6_2.pdf">Orthogonal Sets</a>
<td>   <p>3, 6, 8, 9, 11, 14, 20, 21, 23, 26, 27, 28, 29 
    <!--  <font color="red">HW 5.4 an 6.1 due.</font></p> -->


<TR style="background-color:thistle;"><td> &sect;6.3
<td> 11/15 T
<td> <a href="~troby/math2210f16/LT/sec6_3.pdf">Orthogonal Projections</a>
<td>   <p>1, 6, 7, 9, 11, 13, 17, 21, 23, 24</p>

<TR style="background-color:thistle;"><td> &sect;1.1&ndash;5.2
<td> 11/15 T
<td> Catchup & Review Day
<td> Do <a href="~troby/math2210f16/Handouts/pm2F16.pdf">Practice Midterm 2</a> by today


<tr><th align=center bgcolor="#D8BFD8" colspan=4><font size=4>
<strong> THURSDAY 17 NOVEMBER SECOND MIDTERM EXAM (through &sect;5.3)<br>
   <font color="red">HW  5.4, 6.1 and 6.2 due on TUES 11/29; 6.3 due as usual on THURS 12/1.</font></p> </strong></FONT></th></tr>

<tr><th align=center bgcolor="#AAAAAA" colspan=4><font size=4>
<strong> 25-29 NOVEMBER THANKSGIVING BREAK NO CLASSES  </strong></FONT></th></tr>



<TR style="background-color:aqua;"><td> &sect;6.4
<td> 11/29 T
<td> <a href="~troby/math2210f16/LT/sec6_4.pdf">Gram-Schmidt Process</a>
<td>   <p>1, 3, 7, 9, 11, 17, 19</p>

<TR style="background-color:aqua;"><td> &sect;6.5
<td> 11/29 T
<td> <a href="~troby/math2210f16/LT/sec6_5.pdf">Least-Squares Problems</a>
<td>   <p>3, 5, 7, 9, 11, 17, 19, 21</p>


<TR style="background-color:aqua;"><td> &sect;7.1
<td> 12/1 R
<td> <a href="~troby/math2210f16/Handouts/7-1diagSymmMxs.pdf">Diagonalization of
    Symmetric Matrices</a> 
<td>  <p>1, 3, 5, 8, 10, 13, 17, 19, 25, 29</p>

<TR style="background-color:thistle;"><td> &sect;7.2
<td> 12/6 T
<td> <a href="~troby/math2210f16/Handouts/7-2quadraticFormsStud.pdf">Quadratic Forms</a>
<td>   <p>1, 5, 8, 11, 13, 19, 21, 27 </p>

<TR style="background-color:thistle;"><td> &sect;7.3
<td> 12/6 T
<td> <a href="~troby/math2210f16/LT/dne.html">Constrained Optimization</a>
<td>   <p>1, 3, 5, 7, 11 </p>

<TR style="background-color:thistle;"><td> &sect;7.4
<td> 12/8 R
<td> <a href="~troby/math2210f16/LT/dne.html">Singular Value Decomposition</a>
<td>   <p>1, 3, 9, 11, 17 </p>

<!--  <TR style="background-color:thistle;"><td> &sect;1.1-7.4 -->
<!--  <td> 5/1 R -->
<!--  <td> Catchup & Review Day -->
<!--  <td>  -->

<!--  <tr><th align=center bgcolor="#00FFFF" colspan=4><font size=4> -->
<!--  <strong> TBD  MAY 8:00PM&ndash;10:00PM  FINAL REVIEW IN MSB 215 </strong></FONT> (Do <a href="~troby/math2210f16/Handouts/pf.pdf">Practice Final</a> by today)</th></tr> -->
<tr><th align=center bgcolor="#AAAAAA" colspan=4><font size=4>
<strong>  THURSDAY 15 DECEMBER 3:30&ndash;5:30  FINAL REVIEW IN/NEAR MONT 225 </strong></FONT></th></tr>

<tr><th align=center bgcolor="#AAAAAA" colspan=4><font size=4>
<strong>  SATURDAY 17 DECEMBER 10:30&ndash;12:30  FINAL EXAM IN MONT 225 </strong></FONT></th></tr>
<!--  <strong> <\!--  TUESDAY 6 MAY 10:30&ndash;12:30 -\-> TBD  FINAL EXAM IN MONT 225 </strong></FONT></th></tr> -->
</table>
</center>
</p>
<br>

<HR>

<h3> Web Resources </h3>

<UL>
<LI> <a href="http://buzzard.ups.edu/">Rob Beezer</a> has
  a <a href="http://linear.ups.edu/">free open-source textbook</a> in
  linear algebra that uses the open-source software
  package <a href="http://sagemath.org">Sage</a> for computations.  You can
  download a print edition, or view
  the <a href="http://linear.ups.edu/html/fcla.html">online hyperlinked 
  version</a>.  (This text is geared a bit more for those transitioning to theoretical math
  courses.)  
  <br><br>
  
<li> <a href="http://web.mit.edu/18.06/www/"> The MIT 18.06 (Linear
Algebra) website </a> has lots of resources, including Mathlets (small
web-based teaching tools) (called "Demos" under
  the <a href="http://web.mit.edu/18.06/www/extras.shtml">Extras link</a>.).  
See also <a href="http://math.mit.edu/linearalgebra">resources related to
    Strang's standard textbook <i>Introduction to Linear Algebra</i></a>, in its 5th
  edition as of 2016. (This text is more geared towards applications.) 
<a href="http://math.mit.edu/~gs/">Strang's</a> video lectures are available on YouTube, or cataloged at
the <a href="https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/"> 
MIT 18.06 Course Website for Fall 2011</a>. 
  <br><br>


<LI> <a href="http://math.mercyhurst.edu/~lwilliams/Applets/LinearTransformations.html">A
    Linear Transformation Viewer</a>
    by <a href="http://math.mercyhurst.edu/~lwilliams">Lauren K. Williams</a>.
<br><br>

<li> This is a brief <a href="http://www2.imm.dtu.dk/~pch/Projekter/Google.pdf">blurb on how Google
    ranks pages</a> when you give is a search query and 
a <a href="http://www.ams.org/samplings/feature-column/fcarc-pagerank"> 
more detailed accessible exposition</a>  from
the <a href="http://www.ams.org/samplings/samplings">AMS math samplings website</a>. 
  <br><br>

<li> <a
href="http://www.math.ucla.edu/~tao/resource/general/115a.3.02f/Gauss.html">
A Gaussian Elimination (row reduction) applet from Terry Tao's website </a>
  <br><br>

<li> <a href="http://maven.smith.edu/~patela/Applets/transf_index.html">
A linear transformation applet for the plane from Smith College </a>
  <br><br>

<li> Here's another <a href="http://www.cohomology.com/rref/"> Online
Row Reducer</a> from Greg Landwebber's <a
href="http://www.cohomology.com/">Cohomology.com</a> website. 
  <br><br>

<li> An <a href="http://www.ams.org/samplings/feature-column/fcarc-svd"> elementary exposition of
  the singular value decomposition</a> from
the <a href="http://www.ams.org/samplings/samplings">AMS math samplings website</a>. 
  <br><br>

<LI> Here's
  an <a href="http://www.flashlightcreative.net/swf/mindreader/">Online
  Mind Reader</a>.  Can you figure out how it works?</LI> 
<!--Created by Andy Naughton; search for "online mind reader add digits,
  subtract" -->

</UL>


<HR>
<h3>Anonymous Feedback</h3>

<br>
Use this form to send me anonymous feedback or to answer the question:
<span style="font-weight: bold;">How can I improve your learning in
this class?</span>&nbsp; I will respond to any constructive suggestions
or comments in the space below the form.&nbsp; 
<!-- You can also answer the question below:<br>
<br>
<center>
What's a good question for the midterm?<br>
</center> -->
<form id="MailForm" action=""
      method="post" name="EMailSurvey">
  <input name="Subject" value="Math 2210Q Feedback Fall 2016" type="hidden"> <br>
<!--  <label for="Message">Suggestions:</label><br> -->
<!--  <pre><c></c><table align="center" cellpadding="4" cellspacing="4"> 
<tbody><tr><td><br></td></tr></tbody></table><br><table align="center" cellpadding="0" cellspacing="4"><tbody><tr><td><br><textarea rows="8" cols="100" name="rap"></textarea> <br></td></tr></tbody></table><br></pre>
  <table align="center" cellpadding="0" cellspacing="4">
    <tbody>
      <tr>
        <td> <input value="Send" type="submit"> </td>
        <td><input value="Clear Form" type="reset"> </td>
      </tr>
    </tbody>
  </table> -->
<center>
  <textarea rows="8" cols="100" name="Message"></textarea>
  <br>
  <br>
  <input value="Send" type="submit">
  <input value="Clear Form" type="reset">
</center>
</form>
<br>

<h3> Feedback & Responses </h3>

<ol>


<LI>[Date] <i>This is a test.</i> <br>

<p class="mathpar">This is only a test.</p> </li>



</ol>



<HR>
<h2> NEWS, NOTES, AND HANDOUTS </h2>


<h3>Handouts</h3>

<p>
<UL>
<LI> <a href="~troby/math2210f16/Handouts/pq1.pdf">Practice Quiz #1</a></LI>
<LI> <a href="~troby/math2210f16/Handouts/pq1Soln.pdf">Practice Quiz #1 Solutions</a></LI>
<LI> <a href="~troby/math2210f16/Handouts/pm1F16.pdf">Practice Midterm 1</a></LI>
<LI> <a href="~troby/math2210f16/Handouts/pm1F16Solns.pdf">Solutions to
    Practice Midterm 1</a></LI>

<!--  <LI> <a href="~troby/math2210f16/Handouts/rewrite.pdf">Rules for -->
<!--      Rewrites</a></LI>  -->
<LI> <a href="~troby/math2210f16/Handouts/pm2F16.pdf">Practice Midterm 2</a></LI>
<LI> <a href="~troby/math2210f16/Handouts/pm2F16Solns.pdf">Solutions to
    Practice Midterm 2</a></LI>

<LI> <a href="~troby/math2210f16/Handouts/pfF16.pdf">Practice Final</a></LI>

<LI> <a href="~troby/math2210f16/Handouts/pfF16Solns.pdf">Solutions to Practice Final</a></LI>

</UL>
</p>


<HR>
<p class="mathpar">Back to my <a href="~troby/index.html">home page</a>.<br> </>

</body>
</html>



